//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class ApplicationConverter
    {

        public static ApplicationDto ToDto(this Sam.DataModel.Application source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ApplicationDto ToDtoWithRelated(this Sam.DataModel.Application source, int level)
        {
            if (source == null)
              return null;

            var target = new ApplicationDto();

            // Properties
            target.ApplicationId = source.ApplicationId;
            target.ListId = source.ListId;
            target.PersonId = source.PersonId;
            target.ApplicationUpdate = source.ApplicationUpdate;
            target.PsAdmApplNbr = source.PsAdmApplNbr;
            target.Career = source.Career;
            target.RoundKey = source.RoundKey;
            target.AdmitType = source.AdmitType;
            target.ApplicationAdmitTerm = source.ApplicationAdmitTerm;
            target.SatAdmissionsScore = source.SatAdmissionsScore;
            target.TestType = source.TestType;
            target.TestUpdate = source.TestUpdate;
            target.SatHighestVerifiedMaxCriticalReading = source.SatHighestVerifiedMaxCriticalReading;
            target.SatHighestVerifiedMaxMath = source.SatHighestVerifiedMaxMath;
            target.SatrAdmissionsScore = source.SatrAdmissionsScore;
            target.SatrHighestVerifiedMaxErw = source.SatrHighestVerifiedMaxErw;
            target.SatrHighestVerifiedMaxMath = source.SatrHighestVerifiedMaxMath;
            target.ActHighestVerifiedTotalEnglish = source.ActHighestVerifiedTotalEnglish;
            target.ActHighestVerifiedTotalMath = source.ActHighestVerifiedTotalMath;
            target.RIC = source.RIC;
            target.ERIC = source.ERIC;
            target.DecisionUpdate = source.DecisionUpdate;
            target.DecisionConfirmedDescription = source.DecisionConfirmedDescription;
            target.DecisionConfirmedExport3Code = source.DecisionConfirmedExport3Code;
            target.DecisionConfirmedCode = source.DecisionConfirmedCode;
            target.DecisionConfirmedReasonDescription = source.DecisionConfirmedReasonDescription;
            target.DecisionConfirmedReasonExportKey = source.DecisionConfirmedReasonExportKey;
            target.SchoolUpdate = source.SchoolUpdate;
            target.HsgpaCalculated = source.HsgpaCalculated;
            target.LatestEvaluation = source.LatestEvaluation;
            target.EvaluationStatus = source.EvaluationStatus;
            target.EvalStatusDescr = source.EvalStatusDescr;
            target.Ar = source.Ar;
            target.ArVal = source.ArVal;
            target.Pr = source.Pr;
            target.PrVal = source.PrVal;
            target.Sf = source.Sf;
            target.SfVal = source.SfVal;
            target.Ovr = source.Ovr;
            target.OvrVal = source.OvrVal;
            target.OuaGeoMarket = source.OuaGeoMarket;
            target.OuaRegion = source.OuaRegion;
            target.StaffAssigned = source.StaffAssigned;
            target.EtsCode = source.EtsCode;
            target.HsState = source.HsState;
            target.HsName = source.HsName;
            target.HsRating = source.HsRating;
            target.SchoolOfChoice1 = source.SchoolOfChoice1;
            target.SchoolOfChoice1Descr = source.SchoolOfChoice1Descr;
            target.School1Major1 = source.School1Major1;
            target.School1Major1Descr = source.School1Major1Descr;
            target.GpcMajor = source.GpcMajor;
            target.FinancialAidInterest = source.FinancialAidInterest;
            target.PellEligible = source.PellEligible;
            target.FacStaff = source.FacStaff;
            target.UCode = source.UCode;
            target.Legacy = source.Legacy;
            target.GiaStatus = source.GiaStatus;
            target.FirstGen = source.FirstGen;
            target.Posse = source.Posse;
            target.ChicagoScholar = source.ChicagoScholar;
            target.QuestBridge = source.QuestBridge;
            target.Mosaic = source.Mosaic;
            target.WaitlistActiveDate = source.WaitlistActiveDate;
            target.WlStrong = source.WlStrong;
            target.WaitlistChallenge1 = source.WaitlistChallenge1;
            target.WaitlistChallenge2 = source.WaitlistChallenge2;
            target.WaitlistChallenge3 = source.WaitlistChallenge3;
            target.WaitlistChallenge4 = source.WaitlistChallenge4;
            target.WaitlistChallenge5 = source.WaitlistChallenge5;
            target.WaitlistChallenge6 = source.WaitlistChallenge6;
            target.WaitlistChallenge7 = source.WaitlistChallenge7;
            target.WaitlistChallenge8 = source.WaitlistChallenge8;
            target.WaitlistChallenge9 = source.WaitlistChallenge9;
            target.WaitlistPreOffer = source.WaitlistPreOffer;
            target.WaitlistPreOfferResponse = source.WaitlistPreOfferResponse;
            target.PersonUpdate = source.PersonUpdate;
            target.SlateRefId = source.SlateRefId;
            target.EmplId = source.EmplId;
            target.FirstName = source.FirstName;
            target.LastName = source.LastName;
            target.MiddleName = source.MiddleName;
            target.Sex = source.Sex;
            target.Race = source.Race;
            target.Hispanic = source.Hispanic;
            target.IpedsEthnicCode = source.IpedsEthnicCode;
            target.IpedsEthnicDescr = source.IpedsEthnicDescr;
            target.ProtectionId = source.ProtectionId;
            target.ActAdmissionsScore = source.ActAdmissionsScore;
            target.SchFreeze = source.SchFreeze;
            target.ManualFreeze = source.ManualFreeze;
            target.SOC = source.SOC;
            target.CitizenshipStatus = source.CitizenshipStatus;
            target.PrimaryCitizenshipCountry = source.PrimaryCitizenshipCountry;
            target.SecondaryCitizenshipCountry = source.SecondaryCitizenshipCountry;
            target.Active = source.Active;
            target.LandscapeLocale = source.LandscapeLocale;
            target.LandscapeHSNeighborhood = source.LandscapeHSNeighborhood;
            target.LandscapeStdntNeighborhood = source.LandscapeStdntNeighborhood;
            target.DateOfBirth = source.DateOfBirth;
            target.IsTestingSubmitted = source.IsTestingSubmitted;
            target.CourseworkRigor = source.CourseworkRigor;
            target.WasEver4Year = source.WasEver4Year;
            target.HasMultipleColleges = source.HasMultipleColleges;
            target.NumberOfColleges = source.NumberOfColleges;
            target.HasTakenCalculus = source.HasTakenCalculus;
            target.HasTakenPhysics = source.HasTakenPhysics;
            target.HasTakenChemistry = source.HasTakenChemistry;
            target.CurrentInternationalCollege = source.CurrentInternationalCollege;
            target.CollegeCredits = source.CollegeCredits;
            target.HighSchoolGradYear = source.HighSchoolGradYear;
            target.School1Hours = source.School1Hours;
            target.School2Hours = source.School2Hours;
            target.School3Hours = source.School3Hours;
            target.School4Hours = source.School4Hours;
            target.School1HoursType = source.School1HoursType;
            target.School2HoursType = source.School2HoursType;
            target.School3HoursType = source.School3HoursType;
            target.School4HoursType = source.School4HoursType;
            target.IsDacaUndocumented = source.IsDacaUndocumented;
            target.IsAttendingRuralHs = source.IsAttendingRuralHs;
            target.IsAttendingKippSchool = source.IsAttendingKippSchool;
            target.HasNationalMeritAward = source.HasNationalMeritAward;
            target.IsCGradeCollege = source.IsCGradeCollege;
            target.IsCGradeHighSchool = source.IsCGradeHighSchool;
            target.InstitutionalNeed = source.InstitutionalNeed;
            target.WaitListStrongDate = source.WaitListStrongDate;
            target.OriginalRoundKey = source.OriginalRoundKey;
            target.CorneliusVanderbiltScholarship = source.CorneliusVanderbiltScholarship;
            target.IngramScholarship = source.IngramScholarship;
            target.ChancellorScholarship = source.ChancellorScholarship;
            target.Vv = source.Vv;
            target.VvVal = source.VvVal;
            target.ChDiversity = source.ChDiversity;
            target.ChBridgingGaps = source.ChBridgingGaps;
            target.ChLeadership = source.ChLeadership;
            target.ChOverall = source.ChOverall;
            target.WaitlistLetter = source.WaitlistLetter;
            target.IntlHighSchool = source.IntlHighSchool;
            target.UwcSchool = source.UwcSchool;
            target.TitleOneSchool = source.TitleOneSchool;
            target.WaitlistStrongNumber = source.WaitlistStrongNumber;
            target.Cs = source.Cs;
            target.CsVal = source.CsVal;
            target.Lc = source.Lc;
            target.LcVal = source.LcVal;
            target.Ub = source.Ub;
            target.UbVal = source.UbVal;
            target.DG = source.DG;
            target.HSR = source.HSR;
            target.AppComplete = source.AppComplete;
            target.FocusSchool = source.FocusSchool;

            // Navigation Properties
            if (level > 0) {
              target.List = source.List.ToDtoWithRelated(level - 1);
              target.Protection = source.Protection.ToDtoWithRelated(level - 1);
              target.ListAttributes = source.ListAttributes.ToDtosWithRelated(level - 1);
              target.AuditLog = source.AuditLog.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.Application ToEntity(this ApplicationDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.Application();

            // Properties
            target.ApplicationId = source.ApplicationId;
            target.ListId = source.ListId;
            target.PersonId = source.PersonId;
            target.ApplicationUpdate = source.ApplicationUpdate;
            target.PsAdmApplNbr = source.PsAdmApplNbr;
            target.Career = source.Career;
            target.RoundKey = source.RoundKey;
            target.AdmitType = source.AdmitType;
            target.ApplicationAdmitTerm = source.ApplicationAdmitTerm;
            target.SatAdmissionsScore = source.SatAdmissionsScore;
            target.TestType = source.TestType;
            target.TestUpdate = source.TestUpdate;
            target.SatHighestVerifiedMaxCriticalReading = source.SatHighestVerifiedMaxCriticalReading;
            target.SatHighestVerifiedMaxMath = source.SatHighestVerifiedMaxMath;
            target.SatrAdmissionsScore = source.SatrAdmissionsScore;
            target.SatrHighestVerifiedMaxErw = source.SatrHighestVerifiedMaxErw;
            target.SatrHighestVerifiedMaxMath = source.SatrHighestVerifiedMaxMath;
            target.ActHighestVerifiedTotalEnglish = source.ActHighestVerifiedTotalEnglish;
            target.ActHighestVerifiedTotalMath = source.ActHighestVerifiedTotalMath;
            target.RIC = source.RIC;
            target.ERIC = source.ERIC;
            target.DecisionUpdate = source.DecisionUpdate;
            target.DecisionConfirmedDescription = source.DecisionConfirmedDescription;
            target.DecisionConfirmedExport3Code = source.DecisionConfirmedExport3Code;
            target.DecisionConfirmedCode = source.DecisionConfirmedCode;
            target.DecisionConfirmedReasonDescription = source.DecisionConfirmedReasonDescription;
            target.DecisionConfirmedReasonExportKey = source.DecisionConfirmedReasonExportKey;
            target.SchoolUpdate = source.SchoolUpdate;
            target.HsgpaCalculated = source.HsgpaCalculated;
            target.LatestEvaluation = source.LatestEvaluation;
            target.EvaluationStatus = source.EvaluationStatus;
            target.EvalStatusDescr = source.EvalStatusDescr;
            target.Ar = source.Ar;
            target.ArVal = source.ArVal;
            target.Pr = source.Pr;
            target.PrVal = source.PrVal;
            target.Sf = source.Sf;
            target.SfVal = source.SfVal;
            target.Ovr = source.Ovr;
            target.OvrVal = source.OvrVal;
            target.OuaGeoMarket = source.OuaGeoMarket;
            target.OuaRegion = source.OuaRegion;
            target.StaffAssigned = source.StaffAssigned;
            target.EtsCode = source.EtsCode;
            target.HsState = source.HsState;
            target.HsName = source.HsName;
            target.HsRating = source.HsRating;
            target.SchoolOfChoice1 = source.SchoolOfChoice1;
            target.SchoolOfChoice1Descr = source.SchoolOfChoice1Descr;
            target.School1Major1 = source.School1Major1;
            target.School1Major1Descr = source.School1Major1Descr;
            target.GpcMajor = source.GpcMajor;
            target.FinancialAidInterest = source.FinancialAidInterest;
            target.PellEligible = source.PellEligible;
            target.FacStaff = source.FacStaff;
            target.UCode = source.UCode;
            target.Legacy = source.Legacy;
            target.GiaStatus = source.GiaStatus;
            target.FirstGen = source.FirstGen;
            target.Posse = source.Posse;
            target.ChicagoScholar = source.ChicagoScholar;
            target.QuestBridge = source.QuestBridge;
            target.Mosaic = source.Mosaic;
            target.WaitlistActiveDate = source.WaitlistActiveDate;
            target.WlStrong = source.WlStrong;
            target.WaitlistChallenge1 = source.WaitlistChallenge1;
            target.WaitlistChallenge2 = source.WaitlistChallenge2;
            target.WaitlistChallenge3 = source.WaitlistChallenge3;
            target.WaitlistChallenge4 = source.WaitlistChallenge4;
            target.WaitlistChallenge5 = source.WaitlistChallenge5;
            target.WaitlistChallenge6 = source.WaitlistChallenge6;
            target.WaitlistChallenge7 = source.WaitlistChallenge7;
            target.WaitlistChallenge8 = source.WaitlistChallenge8;
            target.WaitlistChallenge9 = source.WaitlistChallenge9;
            target.WaitlistPreOffer = source.WaitlistPreOffer;
            target.WaitlistPreOfferResponse = source.WaitlistPreOfferResponse;
            target.PersonUpdate = source.PersonUpdate;
            target.SlateRefId = source.SlateRefId;
            target.EmplId = source.EmplId;
            target.FirstName = source.FirstName;
            target.LastName = source.LastName;
            target.MiddleName = source.MiddleName;
            target.Sex = source.Sex;
            target.Race = source.Race;
            target.Hispanic = source.Hispanic;
            target.IpedsEthnicCode = source.IpedsEthnicCode;
            target.IpedsEthnicDescr = source.IpedsEthnicDescr;
            target.ProtectionId = source.ProtectionId;
            target.ActAdmissionsScore = source.ActAdmissionsScore;
            target.SchFreeze = source.SchFreeze;
            target.ManualFreeze = source.ManualFreeze;
            target.SOC = source.SOC;
            target.CitizenshipStatus = source.CitizenshipStatus;
            target.PrimaryCitizenshipCountry = source.PrimaryCitizenshipCountry;
            target.SecondaryCitizenshipCountry = source.SecondaryCitizenshipCountry;
            target.Active = source.Active;
            target.LandscapeLocale = source.LandscapeLocale;
            target.LandscapeHSNeighborhood = source.LandscapeHSNeighborhood;
            target.LandscapeStdntNeighborhood = source.LandscapeStdntNeighborhood;
            target.DateOfBirth = source.DateOfBirth;
            target.IsTestingSubmitted = source.IsTestingSubmitted;
            target.CourseworkRigor = source.CourseworkRigor;
            target.WasEver4Year = source.WasEver4Year;
            target.HasMultipleColleges = source.HasMultipleColleges;
            target.NumberOfColleges = source.NumberOfColleges;
            target.HasTakenCalculus = source.HasTakenCalculus;
            target.HasTakenPhysics = source.HasTakenPhysics;
            target.HasTakenChemistry = source.HasTakenChemistry;
            target.CurrentInternationalCollege = source.CurrentInternationalCollege;
            target.CollegeCredits = source.CollegeCredits;
            target.HighSchoolGradYear = source.HighSchoolGradYear;
            target.School1Hours = source.School1Hours;
            target.School2Hours = source.School2Hours;
            target.School3Hours = source.School3Hours;
            target.School4Hours = source.School4Hours;
            target.School1HoursType = source.School1HoursType;
            target.School2HoursType = source.School2HoursType;
            target.School3HoursType = source.School3HoursType;
            target.School4HoursType = source.School4HoursType;
            target.IsDacaUndocumented = source.IsDacaUndocumented;
            target.IsAttendingRuralHs = source.IsAttendingRuralHs;
            target.IsAttendingKippSchool = source.IsAttendingKippSchool;
            target.HasNationalMeritAward = source.HasNationalMeritAward;
            target.IsCGradeCollege = source.IsCGradeCollege;
            target.IsCGradeHighSchool = source.IsCGradeHighSchool;
            target.InstitutionalNeed = source.InstitutionalNeed;
            target.WaitListStrongDate = source.WaitListStrongDate;
            target.OriginalRoundKey = source.OriginalRoundKey;
            target.CorneliusVanderbiltScholarship = source.CorneliusVanderbiltScholarship;
            target.IngramScholarship = source.IngramScholarship;
            target.ChancellorScholarship = source.ChancellorScholarship;
            target.Vv = source.Vv;
            target.VvVal = source.VvVal;
            target.ChDiversity = source.ChDiversity;
            target.ChBridgingGaps = source.ChBridgingGaps;
            target.ChLeadership = source.ChLeadership;
            target.ChOverall = source.ChOverall;
            target.WaitlistLetter = source.WaitlistLetter;
            target.IntlHighSchool = source.IntlHighSchool;
            target.UwcSchool = source.UwcSchool;
            target.TitleOneSchool = source.TitleOneSchool;
            target.WaitlistStrongNumber = source.WaitlistStrongNumber;
            target.Cs = source.Cs;
            target.CsVal = source.CsVal;
            target.Lc = source.Lc;
            target.LcVal = source.LcVal;
            target.Ub = source.Ub;
            target.UbVal = source.UbVal;
            target.DG = source.DG;
            target.HSR = source.HSR;
            target.AppComplete = source.AppComplete;
            target.FocusSchool = source.FocusSchool;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ApplicationDto> ToDtos(this IEnumerable<Sam.DataModel.Application> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ApplicationDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.Application> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.Application> ToEntities(this IEnumerable<ApplicationDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.Application source, ApplicationDto target);

        static partial void OnEntityCreating(ApplicationDto source, Sam.DataModel.Application target);

    }

}
