//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class AuditLogConverter
    {

        public static AuditLogDto ToDto(this Sam.DataModel.AuditLog source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static AuditLogDto ToDtoWithRelated(this Sam.DataModel.AuditLog source, int level)
        {
            if (source == null)
              return null;

            var target = new AuditLogDto();

            // Properties
            target.Id = source.Id;
            target.ListId = source.ListId;
            target.ApplicationId = source.ApplicationId;
            target.PersonId = source.PersonId;
            target.UserId = source.UserId;
            target.LogDate = source.LogDate;
            target.ProtectionId = source.ProtectionId;
            target.CustomAttributeId = source.CustomAttributeId;
            target.Action = source.Action;

            // Navigation Properties
            if (level > 0) {
              target.Application = source.Application.ToDtoWithRelated(level - 1);
              target.Protection = source.Protection.ToDtoWithRelated(level - 1);
              target.CustomAttribute = source.CustomAttribute.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.AuditLog ToEntity(this AuditLogDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.AuditLog();

            // Properties
            target.Id = source.Id;
            target.ListId = source.ListId;
            target.ApplicationId = source.ApplicationId;
            target.PersonId = source.PersonId;
            target.UserId = source.UserId;
            target.LogDate = source.LogDate;
            target.ProtectionId = source.ProtectionId;
            target.CustomAttributeId = source.CustomAttributeId;
            target.Action = source.Action;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<AuditLogDto> ToDtos(this IEnumerable<Sam.DataModel.AuditLog> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<AuditLogDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.AuditLog> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.AuditLog> ToEntities(this IEnumerable<AuditLogDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.AuditLog source, AuditLogDto target);

        static partial void OnEntityCreating(AuditLogDto source, Sam.DataModel.AuditLog target);

    }

}
