//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class AuditLogDto
    {
        #region Constructors

        public AuditLogDto() {
        }

        public AuditLogDto(long id, int listId, Guid applicationId, Guid personId, int userId, DateTime logDate, int? protectionId, int? customAttributeId, string action, ApplicationDto application, ProtectionDto protection, CustomAttributeDto customAttribute) {

          this.Id = id;
          this.ListId = listId;
          this.ApplicationId = applicationId;
          this.PersonId = personId;
          this.UserId = userId;
          this.LogDate = logDate;
          this.ProtectionId = protectionId;
          this.CustomAttributeId = customAttributeId;
          this.Action = action;
          this.Application = application;
          this.Protection = protection;
          this.CustomAttribute = customAttribute;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public long Id { get; set; }

        [Required()]
        public int ListId { get; set; }

        [Required()]
        public Guid ApplicationId { get; set; }

        [Required()]
        public Guid PersonId { get; set; }

        [Required()]
        public int UserId { get; set; }

        [Required()]
        public DateTime LogDate { get; set; }

        public int? ProtectionId { get; set; }

        public int? CustomAttributeId { get; set; }

        [StringLength(32)]
        [Required()]
        public string Action { get; set; }

        #endregion

        #region Navigation Properties

        public ApplicationDto Application { get; set; }

        public ProtectionDto Protection { get; set; }

        public CustomAttributeDto CustomAttribute { get; set; }

        #endregion
    }

}
