//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class CustomAttributeConverter
    {

        public static CustomAttributeDto ToDto(this Sam.DataModel.CustomAttribute source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static CustomAttributeDto ToDtoWithRelated(this Sam.DataModel.CustomAttribute source, int level)
        {
            if (source == null)
              return null;

            var target = new CustomAttributeDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.CreatedByUserId = source.CreatedByUserId;
            target.CreatedDate = source.CreatedDate;
            target.DeletedDate = source.DeletedDate;

            // Navigation Properties
            if (level > 0) {
              target.ListAttributes = source.ListAttributes.ToDtosWithRelated(level - 1);
              target.User = source.User.ToDtoWithRelated(level - 1);
              target.AuditLogs = source.AuditLogs.ToDtosWithRelated(level - 1);
              target.Queues = source.Queues.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.CustomAttribute ToEntity(this CustomAttributeDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.CustomAttribute();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.CreatedByUserId = source.CreatedByUserId;
            target.CreatedDate = source.CreatedDate;
            target.DeletedDate = source.DeletedDate;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<CustomAttributeDto> ToDtos(this IEnumerable<Sam.DataModel.CustomAttribute> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<CustomAttributeDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.CustomAttribute> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.CustomAttribute> ToEntities(this IEnumerable<CustomAttributeDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.CustomAttribute source, CustomAttributeDto target);

        static partial void OnEntityCreating(CustomAttributeDto source, Sam.DataModel.CustomAttribute target);

    }

}
