//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class CustomAttributeDto
    {
        #region Constructors

        public CustomAttributeDto() {
        }

        public CustomAttributeDto(int id, string name, int? createdByUserId, DateTime? createdDate, DateTime? deletedDate, List<ListAttributeDto> listAttributes, UserDto user, List<AuditLogDto> auditLogs, List<QueueDto> queues) {

          this.Id = id;
          this.Name = name;
          this.CreatedByUserId = createdByUserId;
          this.CreatedDate = createdDate;
          this.DeletedDate = deletedDate;
          this.ListAttributes = listAttributes;
          this.User = user;
          this.AuditLogs = auditLogs;
          this.Queues = queues;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(128)]
        [Required()]
        public string Name { get; set; }

        public int? CreatedByUserId { get; set; }

        public DateTime? CreatedDate { get; set; }

        public DateTime? DeletedDate { get; set; }

        #endregion

        #region Navigation Properties

        public List<ListAttributeDto> ListAttributes { get; set; }

        public UserDto User { get; set; }

        public List<AuditLogDto> AuditLogs { get; set; }

        public List<QueueDto> Queues { get; set; }

        #endregion
    }

}
