//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class DropDownConverter
    {

        public static DropDownDto ToDto(this Sam.DataModel.DropDown source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DropDownDto ToDtoWithRelated(this Sam.DataModel.DropDown source, int level)
        {
            if (source == null)
              return null;

            var target = new DropDownDto();

            // Properties
            target.Id = source.Id;
            target.TypeId = source.TypeId;
            target.Name = source.Name;
            target.Description = source.Description;
            target.Code = source.Code;
            target.FilterValue = source.FilterValue;
            target.Rank = source.Rank;
            target.SortOrder = source.SortOrder;
            target.Display = source.Display;

            // Navigation Properties
            if (level > 0) {
              target.DropDownType = source.DropDownType.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.DropDown ToEntity(this DropDownDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.DropDown();

            // Properties
            target.Id = source.Id;
            target.TypeId = source.TypeId;
            target.Name = source.Name;
            target.Description = source.Description;
            target.Code = source.Code;
            target.FilterValue = source.FilterValue;
            target.Rank = source.Rank;
            target.SortOrder = source.SortOrder;
            target.Display = source.Display;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DropDownDto> ToDtos(this IEnumerable<Sam.DataModel.DropDown> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DropDownDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.DropDown> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.DropDown> ToEntities(this IEnumerable<DropDownDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.DropDown source, DropDownDto target);

        static partial void OnEntityCreating(DropDownDto source, Sam.DataModel.DropDown target);

    }

}
