//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class DropDownTypeDto
    {
        #region Constructors

        public DropDownTypeDto() {
        }

        public DropDownTypeDto(int id, string name, string description, List<DropDownDto> dropDowns) {

          this.Id = id;
          this.Name = name;
          this.Description = description;
          this.DropDowns = dropDowns;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(64)]
        [Required()]
        public string Name { get; set; }

        [StringLength(256)]
        public string Description { get; set; }

        #endregion

        #region Navigation Properties

        public List<DropDownDto> DropDowns { get; set; }

        #endregion
    }

}
