//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class DropDownDto
    {
        #region Constructors

        public DropDownDto() {
        }

        public DropDownDto(int id, int typeId, string name, string description, string code, string filterValue, int? rank, int? sortOrder, bool display, DropDownTypeDto dropDownType) {

          this.Id = id;
          this.TypeId = typeId;
          this.Name = name;
          this.Description = description;
          this.Code = code;
          this.FilterValue = filterValue;
          this.Rank = rank;
          this.SortOrder = sortOrder;
          this.Display = display;
          this.DropDownType = dropDownType;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [Required()]
        public int TypeId { get; set; }

        [StringLength(150)]
        [Required()]
        public string Name { get; set; }

        [StringLength(256)]
        public string Description { get; set; }

        [StringLength(150)]
        public string Code { get; set; }

        [StringLength(32)]
        public string FilterValue { get; set; }

        public int? Rank { get; set; }

        public int? SortOrder { get; set; }

        [Required()]
        public bool Display { get; set; }

        #endregion

        #region Navigation Properties

        public DropDownTypeDto DropDownType { get; set; }

        #endregion
    }

}
