//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class DropDownTypeConverter
    {

        public static DropDownTypeDto ToDto(this Sam.DataModel.DropDownType source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DropDownTypeDto ToDtoWithRelated(this Sam.DataModel.DropDownType source, int level)
        {
            if (source == null)
              return null;

            var target = new DropDownTypeDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.Description = source.Description;

            // Navigation Properties
            if (level > 0) {
              target.DropDowns = source.DropDowns.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.DropDownType ToEntity(this DropDownTypeDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.DropDownType();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.Description = source.Description;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DropDownTypeDto> ToDtos(this IEnumerable<Sam.DataModel.DropDownType> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DropDownTypeDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.DropDownType> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.DropDownType> ToEntities(this IEnumerable<DropDownTypeDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.DropDownType source, DropDownTypeDto target);

        static partial void OnEntityCreating(DropDownTypeDto source, Sam.DataModel.DropDownType target);

    }

}
