//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class FilterAuditLogConverter
    {

        public static FilterAuditLogDto ToDto(this Sam.DataModel.FilterAuditLog source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static FilterAuditLogDto ToDtoWithRelated(this Sam.DataModel.FilterAuditLog source, int level)
        {
            if (source == null)
              return null;

            var target = new FilterAuditLogDto();

            // Properties
            target.Id = source.Id;
            target.ListId = source.ListId;
            target.UserId = source.UserId;
            target.FilterDateTime = source.FilterDateTime;
            target.FilterObject = source.FilterObject;

            // Navigation Properties
            if (level > 0) {
              target.List = source.List.ToDtoWithRelated(level - 1);
              target.User = source.User.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.FilterAuditLog ToEntity(this FilterAuditLogDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.FilterAuditLog();

            // Properties
            target.Id = source.Id;
            target.ListId = source.ListId;
            target.UserId = source.UserId;
            target.FilterDateTime = source.FilterDateTime;
            target.FilterObject = source.FilterObject;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<FilterAuditLogDto> ToDtos(this IEnumerable<Sam.DataModel.FilterAuditLog> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<FilterAuditLogDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.FilterAuditLog> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.FilterAuditLog> ToEntities(this IEnumerable<FilterAuditLogDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.FilterAuditLog source, FilterAuditLogDto target);

        static partial void OnEntityCreating(FilterAuditLogDto source, Sam.DataModel.FilterAuditLog target);

    }

}
