//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class FilterAuditLogDto
    {
        #region Constructors

        public FilterAuditLogDto() {
        }

        public FilterAuditLogDto(int id, int listId, int userId, DateTime filterDateTime, string filterObject, ListDto list, UserDto user) {

          this.Id = id;
          this.ListId = listId;
          this.UserId = userId;
          this.FilterDateTime = filterDateTime;
          this.FilterObject = filterObject;
          this.List = list;
          this.User = user;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [Required()]
        public int ListId { get; set; }

        [Required()]
        public int UserId { get; set; }

        [Required()]
        public DateTime FilterDateTime { get; set; }

        [StringLength(2147483647)]
        [Required()]
        public string FilterObject { get; set; }

        #endregion

        #region Navigation Properties

        public ListDto List { get; set; }

        public UserDto User { get; set; }

        #endregion
    }

}
