//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class HistoricalTargetTypeConverter
    {

        public static HistoricalTargetTypeDto ToDto(this Sam.DataModel.HistoricalTargetType source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static HistoricalTargetTypeDto ToDtoWithRelated(this Sam.DataModel.HistoricalTargetType source, int level)
        {
            if (source == null)
              return null;

            var target = new HistoricalTargetTypeDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.Description = source.Description;

            // Navigation Properties
            if (level > 0) {
              target.HistoricalTargets = source.HistoricalTargets.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.HistoricalTargetType ToEntity(this HistoricalTargetTypeDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.HistoricalTargetType();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.Description = source.Description;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<HistoricalTargetTypeDto> ToDtos(this IEnumerable<Sam.DataModel.HistoricalTargetType> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<HistoricalTargetTypeDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.HistoricalTargetType> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.HistoricalTargetType> ToEntities(this IEnumerable<HistoricalTargetTypeDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.HistoricalTargetType source, HistoricalTargetTypeDto target);

        static partial void OnEntityCreating(HistoricalTargetTypeDto source, Sam.DataModel.HistoricalTargetType target);

    }

}
