//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class HistoricalTargetDto
    {
        #region Constructors

        public HistoricalTargetDto() {
        }

        public HistoricalTargetDto(int id, int historicalTargetTypeId, string cohort, int? count, double? oldSAT, double? newSAT, double? aCT, double? rIC, double? tOP10, int? tN, int? nE, int? mS, int? sO, int? mW, int? sW, int? wS, int? min, int? i, int? a, int? b, int? h, int? p, int? w, int? n, int? multi, int? intl, int? male, int? female, DateTime? effectiveDate, string school, string major, string schoolDivision, string notificationPlanCode, string termNotif, double? iPerc, double? bPerc, double? hPerc, double? pPerc, double? wPerc, int? nA, double? nAPerc, double? multiPerc, double? intlPerc, double? malePerc, double? femalePerc, double? aPerc, double? minPerc, HistoricalTargetTypeDto historicalTargetType) {

          this.Id = id;
          this.HistoricalTargetTypeId = historicalTargetTypeId;
          this.Cohort = cohort;
          this.Count = count;
          this.OldSAT = oldSAT;
          this.NewSAT = newSAT;
          this.ACT = aCT;
          this.RIC = rIC;
          this.TOP10 = tOP10;
          this.TN = tN;
          this.NE = nE;
          this.MS = mS;
          this.SO = sO;
          this.MW = mW;
          this.SW = sW;
          this.WS = wS;
          this.Min = min;
          this.I = i;
          this.A = a;
          this.B = b;
          this.H = h;
          this.P = p;
          this.W = w;
          this.N = n;
          this.Multi = multi;
          this.Intl = intl;
          this.Male = male;
          this.Female = female;
          this.EffectiveDate = effectiveDate;
          this.School = school;
          this.Major = major;
          this.SchoolDivision = schoolDivision;
          this.NotificationPlanCode = notificationPlanCode;
          this.TermNotif = termNotif;
          this.IPerc = iPerc;
          this.BPerc = bPerc;
          this.HPerc = hPerc;
          this.PPerc = pPerc;
          this.WPerc = wPerc;
          this.NA = nA;
          this.NAPerc = nAPerc;
          this.MultiPerc = multiPerc;
          this.IntlPerc = intlPerc;
          this.MalePerc = malePerc;
          this.FemalePerc = femalePerc;
          this.APerc = aPerc;
          this.MinPerc = minPerc;
          this.HistoricalTargetType = historicalTargetType;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [Required()]
        public int HistoricalTargetTypeId { get; set; }

        [StringLength(5)]
        [Required()]
        public string Cohort { get; set; }

        public int? Count { get; set; }

        public double? OldSAT { get; set; }

        public double? NewSAT { get; set; }

        public double? ACT { get; set; }

        public double? RIC { get; set; }

        public double? TOP10 { get; set; }

        public int? TN { get; set; }

        public int? NE { get; set; }

        public int? MS { get; set; }

        public int? SO { get; set; }

        public int? MW { get; set; }

        public int? SW { get; set; }

        public int? WS { get; set; }

        public int? Min { get; set; }

        public int? I { get; set; }

        public int? A { get; set; }

        public int? B { get; set; }

        public int? H { get; set; }

        public int? P { get; set; }

        public int? W { get; set; }

        public int? N { get; set; }

        public int? Multi { get; set; }

        public int? Intl { get; set; }

        public int? Male { get; set; }

        public int? Female { get; set; }

        public DateTime? EffectiveDate { get; set; }

        [StringLength(50)]
        public string School { get; set; }

        [StringLength(50)]
        public string Major { get; set; }

        [StringLength(50)]
        public string SchoolDivision { get; set; }

        [StringLength(50)]
        public string NotificationPlanCode { get; set; }

        [StringLength(50)]
        public string TermNotif { get; set; }

        public double? IPerc { get; set; }

        public double? BPerc { get; set; }

        public double? HPerc { get; set; }

        public double? PPerc { get; set; }

        public double? WPerc { get; set; }

        public int? NA { get; set; }

        public double? NAPerc { get; set; }

        public double? MultiPerc { get; set; }

        public double? IntlPerc { get; set; }

        public double? MalePerc { get; set; }

        public double? FemalePerc { get; set; }

        public double? APerc { get; set; }

        public double? MinPerc { get; set; }

        #endregion

        #region Navigation Properties

        public HistoricalTargetTypeDto HistoricalTargetType { get; set; }

        #endregion
    }

}
