//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class HistoricalTargetConverter
    {

        public static HistoricalTargetDto ToDto(this Sam.DataModel.HistoricalTarget source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static HistoricalTargetDto ToDtoWithRelated(this Sam.DataModel.HistoricalTarget source, int level)
        {
            if (source == null)
              return null;

            var target = new HistoricalTargetDto();

            // Properties
            target.Id = source.Id;
            target.HistoricalTargetTypeId = source.HistoricalTargetTypeId;
            target.Cohort = source.Cohort;
            target.Count = source.Count;
            target.OldSAT = source.OldSAT;
            target.NewSAT = source.NewSAT;
            target.ACT = source.ACT;
            target.RIC = source.RIC;
            target.TOP10 = source.TOP10;
            target.TN = source.TN;
            target.NE = source.NE;
            target.MS = source.MS;
            target.SO = source.SO;
            target.MW = source.MW;
            target.SW = source.SW;
            target.WS = source.WS;
            target.Min = source.Min;
            target.I = source.I;
            target.A = source.A;
            target.B = source.B;
            target.H = source.H;
            target.P = source.P;
            target.W = source.W;
            target.N = source.N;
            target.Multi = source.Multi;
            target.Intl = source.Intl;
            target.Male = source.Male;
            target.Female = source.Female;
            target.EffectiveDate = source.EffectiveDate;
            target.School = source.School;
            target.Major = source.Major;
            target.SchoolDivision = source.SchoolDivision;
            target.NotificationPlanCode = source.NotificationPlanCode;
            target.TermNotif = source.TermNotif;
            target.IPerc = source.IPerc;
            target.BPerc = source.BPerc;
            target.HPerc = source.HPerc;
            target.PPerc = source.PPerc;
            target.WPerc = source.WPerc;
            target.NA = source.NA;
            target.NAPerc = source.NAPerc;
            target.MultiPerc = source.MultiPerc;
            target.IntlPerc = source.IntlPerc;
            target.MalePerc = source.MalePerc;
            target.FemalePerc = source.FemalePerc;
            target.APerc = source.APerc;
            target.MinPerc = source.MinPerc;

            // Navigation Properties
            if (level > 0) {
              target.HistoricalTargetType = source.HistoricalTargetType.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.HistoricalTarget ToEntity(this HistoricalTargetDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.HistoricalTarget();

            // Properties
            target.Id = source.Id;
            target.HistoricalTargetTypeId = source.HistoricalTargetTypeId;
            target.Cohort = source.Cohort;
            target.Count = source.Count;
            target.OldSAT = source.OldSAT;
            target.NewSAT = source.NewSAT;
            target.ACT = source.ACT;
            target.RIC = source.RIC;
            target.TOP10 = source.TOP10;
            target.TN = source.TN;
            target.NE = source.NE;
            target.MS = source.MS;
            target.SO = source.SO;
            target.MW = source.MW;
            target.SW = source.SW;
            target.WS = source.WS;
            target.Min = source.Min;
            target.I = source.I;
            target.A = source.A;
            target.B = source.B;
            target.H = source.H;
            target.P = source.P;
            target.W = source.W;
            target.N = source.N;
            target.Multi = source.Multi;
            target.Intl = source.Intl;
            target.Male = source.Male;
            target.Female = source.Female;
            target.EffectiveDate = source.EffectiveDate;
            target.School = source.School;
            target.Major = source.Major;
            target.SchoolDivision = source.SchoolDivision;
            target.NotificationPlanCode = source.NotificationPlanCode;
            target.TermNotif = source.TermNotif;
            target.IPerc = source.IPerc;
            target.BPerc = source.BPerc;
            target.HPerc = source.HPerc;
            target.PPerc = source.PPerc;
            target.WPerc = source.WPerc;
            target.NA = source.NA;
            target.NAPerc = source.NAPerc;
            target.MultiPerc = source.MultiPerc;
            target.IntlPerc = source.IntlPerc;
            target.MalePerc = source.MalePerc;
            target.FemalePerc = source.FemalePerc;
            target.APerc = source.APerc;
            target.MinPerc = source.MinPerc;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<HistoricalTargetDto> ToDtos(this IEnumerable<Sam.DataModel.HistoricalTarget> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<HistoricalTargetDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.HistoricalTarget> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.HistoricalTarget> ToEntities(this IEnumerable<HistoricalTargetDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.HistoricalTarget source, HistoricalTargetDto target);

        static partial void OnEntityCreating(HistoricalTargetDto source, Sam.DataModel.HistoricalTarget target);

    }

}
