//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class ImportStateConverter
    {

        public static ImportStateDto ToDto(this Sam.DataModel.ImportState source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ImportStateDto ToDtoWithRelated(this Sam.DataModel.ImportState source, int level)
        {
            if (source == null)
              return null;

            var target = new ImportStateDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;

            // Navigation Properties
            if (level > 0) {
              target.ImportAttribs = source.ImportAttribs.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.ImportState ToEntity(this ImportStateDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.ImportState();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ImportStateDto> ToDtos(this IEnumerable<Sam.DataModel.ImportState> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ImportStateDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.ImportState> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.ImportState> ToEntities(this IEnumerable<ImportStateDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.ImportState source, ImportStateDto target);

        static partial void OnEntityCreating(ImportStateDto source, Sam.DataModel.ImportState target);

    }

}
