//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class ImportAttribDto
    {
        #region Constructors

        public ImportAttribDto() {
        }

        public ImportAttribDto(long id, int userId, int importStateId, byte[] spreadsheet, byte[] importLog, DateTime uploadDate, DateTime? importDate, int listId, UserDto user, ImportStateDto importState) {

          this.Id = id;
          this.UserId = userId;
          this.ImportStateId = importStateId;
          this.Spreadsheet = spreadsheet;
          this.ImportLog = importLog;
          this.UploadDate = uploadDate;
          this.ImportDate = importDate;
          this.ListId = listId;
          this.User = user;
          this.ImportState = importState;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public long Id { get; set; }

        [Required()]
        public int UserId { get; set; }

        [Required()]
        public int ImportStateId { get; set; }

        public byte[] Spreadsheet { get; set; }

        public byte[] ImportLog { get; set; }

        [Required()]
        public DateTime UploadDate { get; set; }

        public DateTime? ImportDate { get; set; }

        [Required()]
        public int ListId { get; set; }

        #endregion

        #region Navigation Properties

        public UserDto User { get; set; }

        public ImportStateDto ImportState { get; set; }

        #endregion
    }

}
