//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class ImportAttribConverter
    {

        public static ImportAttribDto ToDto(this Sam.DataModel.ImportAttrib source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ImportAttribDto ToDtoWithRelated(this Sam.DataModel.ImportAttrib source, int level)
        {
            if (source == null)
              return null;

            var target = new ImportAttribDto();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.ImportStateId = source.ImportStateId;
            target.Spreadsheet = source.Spreadsheet;
            target.ImportLog = source.ImportLog;
            target.UploadDate = source.UploadDate;
            target.ImportDate = source.ImportDate;
            target.ListId = source.ListId;

            // Navigation Properties
            if (level > 0) {
              target.User = source.User.ToDtoWithRelated(level - 1);
              target.ImportState = source.ImportState.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.ImportAttrib ToEntity(this ImportAttribDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.ImportAttrib();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.ImportStateId = source.ImportStateId;
            target.Spreadsheet = source.Spreadsheet;
            target.ImportLog = source.ImportLog;
            target.UploadDate = source.UploadDate;
            target.ImportDate = source.ImportDate;
            target.ListId = source.ListId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ImportAttribDto> ToDtos(this IEnumerable<Sam.DataModel.ImportAttrib> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ImportAttribDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.ImportAttrib> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.ImportAttrib> ToEntities(this IEnumerable<ImportAttribDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.ImportAttrib source, ImportAttribDto target);

        static partial void OnEntityCreating(ImportAttribDto source, Sam.DataModel.ImportAttrib target);

    }

}
