//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class ListDto
    {
        #region Constructors

        public ListDto() {
        }

        public ListDto(int id, string name, string cohort, string studentType, DateTime createDate, DateTime? modifyDate, DateTime? lastRefreshDate, bool refreshSuccessful, bool final, List<ApplicationDto> applications, List<ListUserRoleDto> listUserRoles, List<RefreshLogDto> refreshLogs, List<FilterAuditLogDto> filterAuditLogs, List<QueueDto> queues) {

          this.Id = id;
          this.Name = name;
          this.Cohort = cohort;
          this.StudentType = studentType;
          this.CreateDate = createDate;
          this.ModifyDate = modifyDate;
          this.LastRefreshDate = lastRefreshDate;
          this.RefreshSuccessful = refreshSuccessful;
          this.Final = final;
          this.Applications = applications;
          this.ListUserRoles = listUserRoles;
          this.RefreshLogs = refreshLogs;
          this.FilterAuditLogs = filterAuditLogs;
          this.Queues = queues;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(64)]
        [Required()]
        public string Name { get; set; }

        [StringLength(128)]
        public string Cohort { get; set; }

        [StringLength(128)]
        public string StudentType { get; set; }

        [Required()]
        public DateTime CreateDate { get; set; }

        public DateTime? ModifyDate { get; set; }

        public DateTime? LastRefreshDate { get; set; }

        [Required()]
        public bool RefreshSuccessful { get; set; }

        [Required()]
        public bool Final { get; set; }

        #endregion

        #region Navigation Properties

        public List<ApplicationDto> Applications { get; set; }

        public List<ListUserRoleDto> ListUserRoles { get; set; }

        public List<RefreshLogDto> RefreshLogs { get; set; }

        public List<FilterAuditLogDto> FilterAuditLogs { get; set; }

        public List<QueueDto> Queues { get; set; }

        #endregion
    }

}
