//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class ListUserRoleDto
    {
        #region Constructors

        public ListUserRoleDto() {
        }

        public ListUserRoleDto(int listId, int userId, int listRoleId, ListDto list, ListRoleDto listRole, UserDto user) {

          this.ListId = listId;
          this.UserId = userId;
          this.ListRoleId = listRoleId;
          this.List = list;
          this.ListRole = listRole;
          this.User = user;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int ListId { get; set; }

        [Key]
        [Required()]
        public int UserId { get; set; }

        [Key]
        [Required()]
        public int ListRoleId { get; set; }

        #endregion

        #region Navigation Properties

        public ListDto List { get; set; }

        public ListRoleDto ListRole { get; set; }

        public UserDto User { get; set; }

        #endregion
    }

}
