//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class ListRoleConverter
    {

        public static ListRoleDto ToDto(this Sam.DataModel.ListRole source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ListRoleDto ToDtoWithRelated(this Sam.DataModel.ListRole source, int level)
        {
            if (source == null)
              return null;

            var target = new ListRoleDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;

            // Navigation Properties
            if (level > 0) {
              target.ListUserRoles = source.ListUserRoles.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.ListRole ToEntity(this ListRoleDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.ListRole();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ListRoleDto> ToDtos(this IEnumerable<Sam.DataModel.ListRole> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ListRoleDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.ListRole> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.ListRole> ToEntities(this IEnumerable<ListRoleDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.ListRole source, ListRoleDto target);

        static partial void OnEntityCreating(ListRoleDto source, Sam.DataModel.ListRole target);

    }

}
