//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class ListUserRoleConverter
    {

        public static ListUserRoleDto ToDto(this Sam.DataModel.ListUserRole source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ListUserRoleDto ToDtoWithRelated(this Sam.DataModel.ListUserRole source, int level)
        {
            if (source == null)
              return null;

            var target = new ListUserRoleDto();

            // Properties
            target.ListId = source.ListId;
            target.UserId = source.UserId;
            target.ListRoleId = source.ListRoleId;

            // Navigation Properties
            if (level > 0) {
              target.List = source.List.ToDtoWithRelated(level - 1);
              target.ListRole = source.ListRole.ToDtoWithRelated(level - 1);
              target.User = source.User.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.ListUserRole ToEntity(this ListUserRoleDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.ListUserRole();

            // Properties
            target.ListId = source.ListId;
            target.UserId = source.UserId;
            target.ListRoleId = source.ListRoleId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ListUserRoleDto> ToDtos(this IEnumerable<Sam.DataModel.ListUserRole> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ListUserRoleDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.ListUserRole> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.ListUserRole> ToEntities(this IEnumerable<ListUserRoleDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.ListUserRole source, ListUserRoleDto target);

        static partial void OnEntityCreating(ListUserRoleDto source, Sam.DataModel.ListUserRole target);

    }

}
