//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class ListAttributeConverter
    {

        public static ListAttributeDto ToDto(this Sam.DataModel.ListAttribute source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ListAttributeDto ToDtoWithRelated(this Sam.DataModel.ListAttribute source, int level)
        {
            if (source == null)
              return null;

            var target = new ListAttributeDto();

            // Properties
            target.ListId = source.ListId;
            target.ApplicationId = source.ApplicationId;
            target.PersonId = source.PersonId;
            target.AttributeId = source.AttributeId;
            target.LastModifyUserId = source.LastModifyUserId;
            target.LastModifyDate = source.LastModifyDate;

            // Navigation Properties
            if (level > 0) {
              target.CustomAttribute = source.CustomAttribute.ToDtoWithRelated(level - 1);
              target.Application = source.Application.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.ListAttribute ToEntity(this ListAttributeDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.ListAttribute();

            // Properties
            target.ListId = source.ListId;
            target.ApplicationId = source.ApplicationId;
            target.PersonId = source.PersonId;
            target.AttributeId = source.AttributeId;
            target.LastModifyUserId = source.LastModifyUserId;
            target.LastModifyDate = source.LastModifyDate;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ListAttributeDto> ToDtos(this IEnumerable<Sam.DataModel.ListAttribute> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ListAttributeDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.ListAttribute> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.ListAttribute> ToEntities(this IEnumerable<ListAttributeDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.ListAttribute source, ListAttributeDto target);

        static partial void OnEntityCreating(ListAttributeDto source, Sam.DataModel.ListAttribute target);

    }

}
