//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class ListAttributeDto
    {
        #region Constructors

        public ListAttributeDto() {
        }

        public ListAttributeDto(int listId, Guid applicationId, Guid personId, int attributeId, int lastModifyUserId, DateTime lastModifyDate, CustomAttributeDto customAttribute, ApplicationDto application) {

          this.ListId = listId;
          this.ApplicationId = applicationId;
          this.PersonId = personId;
          this.AttributeId = attributeId;
          this.LastModifyUserId = lastModifyUserId;
          this.LastModifyDate = lastModifyDate;
          this.CustomAttribute = customAttribute;
          this.Application = application;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int ListId { get; set; }

        [Key]
        [Required()]
        public Guid ApplicationId { get; set; }

        [Key]
        [Required()]
        public Guid PersonId { get; set; }

        [Key]
        [Required()]
        public int AttributeId { get; set; }

        [Required()]
        public int LastModifyUserId { get; set; }

        [Required()]
        public DateTime LastModifyDate { get; set; }

        #endregion

        #region Navigation Properties

        public CustomAttributeDto CustomAttribute { get; set; }

        public ApplicationDto Application { get; set; }

        #endregion
    }

}
