//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class ProtectionDto
    {
        #region Constructors

        public ProtectionDto() {
        }

        public ProtectionDto(int id, string name, string description, List<AuditLogDto> auditLogs, List<QueueDto> queues) {

          this.Id = id;
          this.Name = name;
          this.Description = description;
          this.AuditLogs = auditLogs;
          this.Queues = queues;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(64)]
        [Required()]
        public string Name { get; set; }

        [StringLength(256)]
        public string Description { get; set; }

        #endregion

        #region Navigation Properties

        public List<AuditLogDto> AuditLogs { get; set; }

        public List<QueueDto> Queues { get; set; }

        #endregion
    }

}
