//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class ProtectionConverter
    {

        public static ProtectionDto ToDto(this Sam.DataModel.Protection source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ProtectionDto ToDtoWithRelated(this Sam.DataModel.Protection source, int level)
        {
            if (source == null)
              return null;

            var target = new ProtectionDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.Description = source.Description;

            // Navigation Properties
            if (level > 0) {
              target.AuditLogs = source.AuditLogs.ToDtosWithRelated(level - 1);
              target.Queues = source.Queues.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.Protection ToEntity(this ProtectionDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.Protection();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.Description = source.Description;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ProtectionDto> ToDtos(this IEnumerable<Sam.DataModel.Protection> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ProtectionDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.Protection> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.Protection> ToEntities(this IEnumerable<ProtectionDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.Protection source, ProtectionDto target);

        static partial void OnEntityCreating(ProtectionDto source, Sam.DataModel.Protection target);

    }

}
