//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class QueueConverter
    {

        public static QueueDto ToDto(this Sam.DataModel.Queue source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static QueueDto ToDtoWithRelated(this Sam.DataModel.Queue source, int level)
        {
            if (source == null)
              return null;

            var target = new QueueDto();

            // Properties
            target.Id = source.Id;
            target.QueueTypeId = source.QueueTypeId;
            target.UserId = source.UserId;
            target.ListId = source.ListId;
            target.DateSubmitted = source.DateSubmitted;
            target.LastUpdate = source.LastUpdate;
            target.DateStart = source.DateStart;
            target.DateEnd = source.DateEnd;
            target.TotalRows = source.TotalRows;
            target.CurrentRow = source.CurrentRow;
            target.IsDelete = source.IsDelete;
            target.IsJson = source.IsJson;
            target.RecordString = source.RecordString;
            target.ActionTitle = source.ActionTitle;
            target.IsError = source.IsError;
            target.ProtectionId = source.ProtectionId;
            target.CustomAttributeId = source.CustomAttributeId;
            target.Message = source.Message;

            // Navigation Properties
            if (level > 0) {
              target.User = source.User.ToDtoWithRelated(level - 1);
              target.List = source.List.ToDtoWithRelated(level - 1);
              target.Protection = source.Protection.ToDtoWithRelated(level - 1);
              target.CustomAttribute = source.CustomAttribute.ToDtoWithRelated(level - 1);
              target.QueueType = source.QueueType.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.Queue ToEntity(this QueueDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.Queue();

            // Properties
            target.Id = source.Id;
            target.QueueTypeId = source.QueueTypeId;
            target.UserId = source.UserId;
            target.ListId = source.ListId;
            target.DateSubmitted = source.DateSubmitted;
            target.LastUpdate = source.LastUpdate;
            target.DateStart = source.DateStart;
            target.DateEnd = source.DateEnd;
            target.TotalRows = source.TotalRows;
            target.CurrentRow = source.CurrentRow;
            target.IsDelete = source.IsDelete;
            target.IsJson = source.IsJson;
            target.RecordString = source.RecordString;
            target.ActionTitle = source.ActionTitle;
            target.IsError = source.IsError;
            target.ProtectionId = source.ProtectionId;
            target.CustomAttributeId = source.CustomAttributeId;
            target.Message = source.Message;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<QueueDto> ToDtos(this IEnumerable<Sam.DataModel.Queue> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<QueueDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.Queue> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.Queue> ToEntities(this IEnumerable<QueueDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.Queue source, QueueDto target);

        static partial void OnEntityCreating(QueueDto source, Sam.DataModel.Queue target);

    }

}
