//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class QueueDto
    {
        #region Constructors

        public QueueDto() {
        }

        public QueueDto(int id, int queueTypeId, int userId, int listId, DateTime dateSubmitted, DateTime? lastUpdate, DateTime? dateStart, DateTime? dateEnd, int? totalRows, int? currentRow, bool isDelete, bool isJson, string recordString, string actionTitle, bool isError, int? protectionId, int? customAttributeId, string message, UserDto user, ListDto list, ProtectionDto protection, CustomAttributeDto customAttribute, QueueTypeDto queueType) {

          this.Id = id;
          this.QueueTypeId = queueTypeId;
          this.UserId = userId;
          this.ListId = listId;
          this.DateSubmitted = dateSubmitted;
          this.LastUpdate = lastUpdate;
          this.DateStart = dateStart;
          this.DateEnd = dateEnd;
          this.TotalRows = totalRows;
          this.CurrentRow = currentRow;
          this.IsDelete = isDelete;
          this.IsJson = isJson;
          this.RecordString = recordString;
          this.ActionTitle = actionTitle;
          this.IsError = isError;
          this.ProtectionId = protectionId;
          this.CustomAttributeId = customAttributeId;
          this.Message = message;
          this.User = user;
          this.List = list;
          this.Protection = protection;
          this.CustomAttribute = customAttribute;
          this.QueueType = queueType;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [Required()]
        public int QueueTypeId { get; set; }

        [Required()]
        public int UserId { get; set; }

        [Required()]
        public int ListId { get; set; }

        [Required()]
        public DateTime DateSubmitted { get; set; }

        public DateTime? LastUpdate { get; set; }

        public DateTime? DateStart { get; set; }

        public DateTime? DateEnd { get; set; }

        public int? TotalRows { get; set; }

        public int? CurrentRow { get; set; }

        [Required()]
        public bool IsDelete { get; set; }

        [Required()]
        public bool IsJson { get; set; }

        [Required()]
        public string RecordString { get; set; }

        [StringLength(128)]
        [Required()]
        public string ActionTitle { get; set; }

        [Required()]
        public bool IsError { get; set; }

        public int? ProtectionId { get; set; }

        public int? CustomAttributeId { get; set; }

        [StringLength(2048)]
        public string Message { get; set; }

        #endregion

        #region Navigation Properties

        public UserDto User { get; set; }

        public ListDto List { get; set; }

        public ProtectionDto Protection { get; set; }

        public CustomAttributeDto CustomAttribute { get; set; }

        public QueueTypeDto QueueType { get; set; }

        #endregion
    }

}
