//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class QueueTypeDto
    {
        #region Constructors

        public QueueTypeDto() {
        }

        public QueueTypeDto(int id, string name, bool isActive, int sortOrder, List<QueueDto> queues) {

          this.Id = id;
          this.Name = name;
          this.IsActive = isActive;
          this.SortOrder = sortOrder;
          this.Queues = queues;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [Required()]
        public string Name { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        [Required()]
        public int SortOrder { get; set; }

        #endregion

        #region Navigation Properties

        public List<QueueDto> Queues { get; set; }

        #endregion
    }

}
