//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class QueueTypeConverter
    {

        public static QueueTypeDto ToDto(this Sam.DataModel.QueueType source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static QueueTypeDto ToDtoWithRelated(this Sam.DataModel.QueueType source, int level)
        {
            if (source == null)
              return null;

            var target = new QueueTypeDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.IsActive = source.IsActive;
            target.SortOrder = source.SortOrder;

            // Navigation Properties
            if (level > 0) {
              target.Queues = source.Queues.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.QueueType ToEntity(this QueueTypeDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.QueueType();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.IsActive = source.IsActive;
            target.SortOrder = source.SortOrder;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<QueueTypeDto> ToDtos(this IEnumerable<Sam.DataModel.QueueType> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<QueueTypeDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.QueueType> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.QueueType> ToEntities(this IEnumerable<QueueTypeDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.QueueType source, QueueTypeDto target);

        static partial void OnEntityCreating(QueueTypeDto source, Sam.DataModel.QueueType target);

    }

}
