//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class RefreshStateConverter
    {

        public static RefreshStateDto ToDto(this Sam.DataModel.RefreshState source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static RefreshStateDto ToDtoWithRelated(this Sam.DataModel.RefreshState source, int level)
        {
            if (source == null)
              return null;

            var target = new RefreshStateDto();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;

            // Navigation Properties
            if (level > 0) {
              target.RefreshLogs = source.RefreshLogs.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.RefreshState ToEntity(this RefreshStateDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.RefreshState();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<RefreshStateDto> ToDtos(this IEnumerable<Sam.DataModel.RefreshState> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<RefreshStateDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.RefreshState> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.RefreshState> ToEntities(this IEnumerable<RefreshStateDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.RefreshState source, RefreshStateDto target);

        static partial void OnEntityCreating(RefreshStateDto source, Sam.DataModel.RefreshState target);

    }

}
