//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class RefreshLogDto
    {
        #region Constructors

        public RefreshLogDto() {
        }

        public RefreshLogDto(int id, int userId, int listId, DateTime startTimeStamp, DateTime? endTimeStamp, bool successful, int refreshStateId, string jobName, Guid? jobId, bool? copy, int? sourceList, string errorMessage, ListDto list, RefreshStateDto refreshState, UserDto user) {

          this.Id = id;
          this.UserId = userId;
          this.ListId = listId;
          this.StartTimeStamp = startTimeStamp;
          this.EndTimeStamp = endTimeStamp;
          this.Successful = successful;
          this.RefreshStateId = refreshStateId;
          this.JobName = jobName;
          this.JobId = jobId;
          this.Copy = copy;
          this.SourceList = sourceList;
          this.ErrorMessage = errorMessage;
          this.List = list;
          this.RefreshState = refreshState;
          this.User = user;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [Required()]
        public int UserId { get; set; }

        [Required()]
        public int ListId { get; set; }

        [Required()]
        public DateTime StartTimeStamp { get; set; }

        public DateTime? EndTimeStamp { get; set; }

        [Required()]
        public bool Successful { get; set; }

        [Required()]
        public int RefreshStateId { get; set; }

        [StringLength(512)]
        public string JobName { get; set; }

        public Guid? JobId { get; set; }

        public bool? Copy { get; set; }

        public int? SourceList { get; set; }

        [StringLength(255)]
        public string ErrorMessage { get; set; }

        #endregion

        #region Navigation Properties

        public ListDto List { get; set; }

        public RefreshStateDto RefreshState { get; set; }

        public UserDto User { get; set; }

        #endregion
    }

}
