//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class RefreshStateDto
    {
        #region Constructors

        public RefreshStateDto() {
        }

        public RefreshStateDto(int id, string name, List<RefreshLogDto> refreshLogs) {

          this.Id = id;
          this.Name = name;
          this.RefreshLogs = refreshLogs;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(50)]
        [Required()]
        public string Name { get; set; }

        #endregion

        #region Navigation Properties

        public List<RefreshLogDto> RefreshLogs { get; set; }

        #endregion
    }

}
