//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class RefreshLogConverter
    {

        public static RefreshLogDto ToDto(this Sam.DataModel.RefreshLog source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static RefreshLogDto ToDtoWithRelated(this Sam.DataModel.RefreshLog source, int level)
        {
            if (source == null)
              return null;

            var target = new RefreshLogDto();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.ListId = source.ListId;
            target.StartTimeStamp = source.StartTimeStamp;
            target.EndTimeStamp = source.EndTimeStamp;
            target.Successful = source.Successful;
            target.RefreshStateId = source.RefreshStateId;
            target.JobName = source.JobName;
            target.JobId = source.JobId;
            target.Copy = source.Copy;
            target.SourceList = source.SourceList;
            target.ErrorMessage = source.ErrorMessage;

            // Navigation Properties
            if (level > 0) {
              target.List = source.List.ToDtoWithRelated(level - 1);
              target.RefreshState = source.RefreshState.ToDtoWithRelated(level - 1);
              target.User = source.User.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.RefreshLog ToEntity(this RefreshLogDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.RefreshLog();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.ListId = source.ListId;
            target.StartTimeStamp = source.StartTimeStamp;
            target.EndTimeStamp = source.EndTimeStamp;
            target.Successful = source.Successful;
            target.RefreshStateId = source.RefreshStateId;
            target.JobName = source.JobName;
            target.JobId = source.JobId;
            target.Copy = source.Copy;
            target.SourceList = source.SourceList;
            target.ErrorMessage = source.ErrorMessage;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<RefreshLogDto> ToDtos(this IEnumerable<Sam.DataModel.RefreshLog> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<RefreshLogDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.RefreshLog> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.RefreshLog> ToEntities(this IEnumerable<RefreshLogDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.RefreshLog source, RefreshLogDto target);

        static partial void OnEntityCreating(RefreshLogDto source, Sam.DataModel.RefreshLog target);

    }

}
