//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class RoleDto
    {
        #region Constructors

        public RoleDto() {
        }

        public RoleDto(int id, string name, List<UserRoleDto> userRoles) {

          this.Id = id;
          this.Name = name;
          this.UserRoles = userRoles;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(32)]
        [Required()]
        public string Name { get; set; }

        #endregion

        #region Navigation Properties

        public List<UserRoleDto> UserRoles { get; set; }

        #endregion
    }

}
