//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class SavedObjectDto
    {
        #region Constructors

        public SavedObjectDto() {
        }

        public SavedObjectDto(int id, int userId, string name, string description, string storedObject, UserDto user) {

          this.Id = id;
          this.UserId = userId;
          this.Name = name;
          this.Description = description;
          this.StoredObject = storedObject;
          this.User = user;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [Required()]
        public int UserId { get; set; }

        [StringLength(128)]
        [Required()]
        public string Name { get; set; }

        [StringLength(256)]
        public string Description { get; set; }

        [StringLength(2147483647)]
        [Required()]
        public string StoredObject { get; set; }

        #endregion

        #region Navigation Properties

        public UserDto User { get; set; }

        #endregion
    }

}
