//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class SavedObjectConverter
    {

        public static SavedObjectDto ToDto(this Sam.DataModel.SavedObject source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static SavedObjectDto ToDtoWithRelated(this Sam.DataModel.SavedObject source, int level)
        {
            if (source == null)
              return null;

            var target = new SavedObjectDto();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.Name = source.Name;
            target.Description = source.Description;
            target.StoredObject = source.StoredObject;

            // Navigation Properties
            if (level > 0) {
              target.User = source.User.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.SavedObject ToEntity(this SavedObjectDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.SavedObject();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.Name = source.Name;
            target.Description = source.Description;
            target.StoredObject = source.StoredObject;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<SavedObjectDto> ToDtos(this IEnumerable<Sam.DataModel.SavedObject> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<SavedObjectDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.SavedObject> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.SavedObject> ToEntities(this IEnumerable<SavedObjectDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.SavedObject source, SavedObjectDto target);

        static partial void OnEntityCreating(SavedObjectDto source, Sam.DataModel.SavedObject target);

    }

}
