//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class UserRoleDto
    {
        #region Constructors

        public UserRoleDto() {
        }

        public UserRoleDto(int userId, int roleId, RoleDto role, UserDto user) {

          this.UserId = userId;
          this.RoleId = roleId;
          this.Role = role;
          this.User = user;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int UserId { get; set; }

        [Key]
        [Required()]
        public int RoleId { get; set; }

        #endregion

        #region Navigation Properties

        public RoleDto Role { get; set; }

        public UserDto User { get; set; }

        #endregion
    }

}
