//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class UserRoleConverter
    {

        public static UserRoleDto ToDto(this Sam.DataModel.UserRole source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static UserRoleDto ToDtoWithRelated(this Sam.DataModel.UserRole source, int level)
        {
            if (source == null)
              return null;

            var target = new UserRoleDto();

            // Properties
            target.UserId = source.UserId;
            target.RoleId = source.RoleId;

            // Navigation Properties
            if (level > 0) {
              target.Role = source.Role.ToDtoWithRelated(level - 1);
              target.User = source.User.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.UserRole ToEntity(this UserRoleDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.UserRole();

            // Properties
            target.UserId = source.UserId;
            target.RoleId = source.RoleId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<UserRoleDto> ToDtos(this IEnumerable<Sam.DataModel.UserRole> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<UserRoleDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.UserRole> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.UserRole> ToEntities(this IEnumerable<UserRoleDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.UserRole source, UserRoleDto target);

        static partial void OnEntityCreating(UserRoleDto source, Sam.DataModel.UserRole target);

    }

}
