//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class UserDto
    {
        #region Constructors

        public UserDto() {
        }

        public UserDto(int id, string vuNetId, string firstName, string lastName, string email, string createUser, DateTime createDate, DateTime? lastLoginDate, int? lastListId, List<CustomAttributeDto> customAttributes, List<ListUserRoleDto> listUserRoles, List<RefreshLogDto> refreshLogs, List<UserRoleDto> userRoles, List<SavedObjectDto> savedObjects, List<ImportAttribDto> importAttribs, List<FilterAuditLogDto> filterAuditLogs, List<QueueDto> queues) {

          this.Id = id;
          this.VuNetId = vuNetId;
          this.FirstName = firstName;
          this.LastName = lastName;
          this.Email = email;
          this.CreateUser = createUser;
          this.CreateDate = createDate;
          this.LastLoginDate = lastLoginDate;
          this.LastListId = lastListId;
          this.CustomAttributes = customAttributes;
          this.ListUserRoles = listUserRoles;
          this.RefreshLogs = refreshLogs;
          this.UserRoles = userRoles;
          this.SavedObjects = savedObjects;
          this.ImportAttribs = importAttribs;
          this.FilterAuditLogs = filterAuditLogs;
          this.Queues = queues;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(16)]
        [Required()]
        public string VuNetId { get; set; }

        [StringLength(64)]
        [Required()]
        public string FirstName { get; set; }

        [StringLength(64)]
        [Required()]
        public string LastName { get; set; }

        [StringLength(256)]
        [Required()]
        public string Email { get; set; }

        [StringLength(16)]
        [Required()]
        public string CreateUser { get; set; }

        [Required()]
        public DateTime CreateDate { get; set; }

        public DateTime? LastLoginDate { get; set; }

        public int? LastListId { get; set; }

        #endregion

        #region Navigation Properties

        public List<CustomAttributeDto> CustomAttributes { get; set; }

        public List<ListUserRoleDto> ListUserRoles { get; set; }

        public List<RefreshLogDto> RefreshLogs { get; set; }

        public List<UserRoleDto> UserRoles { get; set; }

        public List<SavedObjectDto> SavedObjects { get; set; }

        public List<ImportAttribDto> ImportAttribs { get; set; }

        public List<FilterAuditLogDto> FilterAuditLogs { get; set; }

        public List<QueueDto> Queues { get; set; }

        #endregion
    }

}
