//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class UserConverter
    {

        public static UserDto ToDto(this Sam.DataModel.User source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static UserDto ToDtoWithRelated(this Sam.DataModel.User source, int level)
        {
            if (source == null)
              return null;

            var target = new UserDto();

            // Properties
            target.Id = source.Id;
            target.VuNetId = source.VuNetId;
            target.FirstName = source.FirstName;
            target.LastName = source.LastName;
            target.Email = source.Email;
            target.CreateUser = source.CreateUser;
            target.CreateDate = source.CreateDate;
            target.LastLoginDate = source.LastLoginDate;
            target.LastListId = source.LastListId;

            // Navigation Properties
            if (level > 0) {
              target.CustomAttributes = source.CustomAttributes.ToDtosWithRelated(level - 1);
              target.ListUserRoles = source.ListUserRoles.ToDtosWithRelated(level - 1);
              target.RefreshLogs = source.RefreshLogs.ToDtosWithRelated(level - 1);
              target.UserRoles = source.UserRoles.ToDtosWithRelated(level - 1);
              target.SavedObjects = source.SavedObjects.ToDtosWithRelated(level - 1);
              target.ImportAttribs = source.ImportAttribs.ToDtosWithRelated(level - 1);
              target.FilterAuditLogs = source.FilterAuditLogs.ToDtosWithRelated(level - 1);
              target.Queues = source.Queues.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.User ToEntity(this UserDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.User();

            // Properties
            target.Id = source.Id;
            target.VuNetId = source.VuNetId;
            target.FirstName = source.FirstName;
            target.LastName = source.LastName;
            target.Email = source.Email;
            target.CreateUser = source.CreateUser;
            target.CreateDate = source.CreateDate;
            target.LastLoginDate = source.LastLoginDate;
            target.LastListId = source.LastListId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<UserDto> ToDtos(this IEnumerable<Sam.DataModel.User> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<UserDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.User> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.User> ToEntities(this IEnumerable<UserDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.User source, UserDto target);

        static partial void OnEntityCreating(UserDto source, Sam.DataModel.User target);

    }

}
