//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class VwCombinedAppPoolConverter
    {

        public static VwCombinedAppPoolDto ToDto(this Sam.DataModel.VwCombinedAppPool source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static VwCombinedAppPoolDto ToDtoWithRelated(this Sam.DataModel.VwCombinedAppPool source, int level)
        {
            if (source == null)
              return null;

            var target = new VwCombinedAppPoolDto();

            // Properties
            target.APPLICATIONID = source.APPLICATIONID;
            target.PERSONID = source.PERSONID;
            target.SLATEREFID = source.SLATEREFID;
            target.EMPLID = source.EMPLID;
            target.PSADMAPPLNBR = source.PSADMAPPLNBR;
            target.FIRSTNAME = source.FIRSTNAME;
            target.MIDDLENAME = source.MIDDLENAME;
            target.LASTNAME = source.LASTNAME;
            target.SEX = source.SEX;
            target.DOB = source.DOB;
            target.SOC = source.SOC;
            target.IPEDSETHNICCODE = source.IPEDSETHNICCODE;
            target.CITIZENSHIPSTATUS = source.CITIZENSHIPSTATUS;
            target.PRIMARYCITIZENSHIPCOUNTRY = source.PRIMARYCITIZENSHIPCOUNTRY;
            target.SECONDARYCITIZENSHIPCOUNTRY = source.SECONDARYCITIZENSHIPCOUNTRY;
            target.ROUNDKEY = source.ROUNDKEY;
            target.ADMITTYPE = source.ADMITTYPE;
            target.DECISIONCONFIRMEDDESCR = source.DECISIONCONFIRMEDDESCR;
            target.DECISIONCONFIRMEDREASONDESCR = source.DECISIONCONFIRMEDREASONDESCR;
            target.DECISIONCONFIRMEDCODE = source.DECISIONCONFIRMEDCODE;
            target.DECISIONCONFIRMEDREASONEXPORTKEY = source.DECISIONCONFIRMEDREASONEXPORTKEY;
            target.APPLICATIONADMITTERM = source.APPLICATIONADMITTERM;
            target.OUAGEOMARKET = source.OUAGEOMARKET;
            target.OUAREGION = source.OUAREGION;
            target.HSNAME = source.HSNAME;
            target.STAFFASSIGNED = source.STAFFASSIGNED;
            target.ETSCODE = source.ETSCODE;
            target.HSSTATE = source.HSSTATE;
            target.HSRATING = source.HSRATING;
            target.SCHOOLOFCHOICE1 = source.SCHOOLOFCHOICE1;
            target.SCHOOLOFCHOICE1DESCR = source.SCHOOLOFCHOICE1DESCR;
            target.SCHOOL1MAJOR1 = source.SCHOOL1MAJOR1;
            target.SCHOOL1MAJOR1DESCR = source.SCHOOL1MAJOR1DESCR;
            target.GPCMAJOR = source.GPCMAJOR;
            target.FINANCIALAIDINTEREST = source.FINANCIALAIDINTEREST;
            target.PELLELIGIBLE = source.PELLELIGIBLE;
            target.FACSTAFF = source.FACSTAFF;
            target.LEGACY = source.LEGACY;
            target.GIASTATUS = source.GIASTATUS;
            target.FIRSTGEN = source.FIRSTGEN;
            target.POSSE = source.POSSE;
            target.CHICAGOSCHOLAR = source.CHICAGOSCHOLAR;
            target.QUESTBRIDGE = source.QUESTBRIDGE;
            target.MOSAIC = source.MOSAIC;
            target.SCHFREEZE = source.SCHFREEZE;
            target.CORNELIUSVANDERBILTAPPLIED = source.CORNELIUSVANDERBILTAPPLIED;
            target.INGRAMAPPLIED = source.INGRAMAPPLIED;
            target.CHANCELLORSAPPLIED = source.CHANCELLORSAPPLIED;
            target.APPLICATIONUPDATE = source.APPLICATIONUPDATE;
            target.PERSONUPDATE = source.PERSONUPDATE;
            target.DECISIONUPDATE = source.DECISIONUPDATE;
            target.ACTUPDATE = source.ACTUPDATE;
            target.SCHOOLUPDATE = source.SCHOOLUPDATE;
            target.LANDSCAPEHSNEIGHBORHOOD = source.LANDSCAPEHSNEIGHBORHOOD;
            target.LANDSCAPESTDNTNEIGHBORHOOD = source.LANDSCAPESTDNTNEIGHBORHOOD;
            target.SUBMITTINGTESTING = source.SUBMITTINGTESTING;
            target.COURSEWORKRIGOR = source.COURSEWORKRIGOR;
            target.RURALHS = source.RURALHS;
            target.DACAUNDOCUMENTED = source.DACAUNDOCUMENTED;
            target.KIPP = source.KIPP;
            target.NATLMERITAWARD = source.NATLMERITAWARD;
            target.CGRADEHS = source.CGRADEHS;
            target.CGRADECOL = source.CGRADECOL;
            target.INSTITUTIONALNEED = source.INSTITUTIONALNEED;
            target.ORIGINALROUNDAPPLIED = source.ORIGINALROUNDAPPLIED;
            target.CHDIVERSITY = source.CHDIVERSITY;
            target.CHBRIDGINGGAPS = source.CHBRIDGINGGAPS;
            target.CHLEADERSHIP = source.CHLEADERSHIP;
            target.CHOVERALL = source.CHOVERALL;
            target.WAITLISTLETTER = source.WAITLISTLETTER;
            target.INTLHIGHSCHOOL = source.INTLHIGHSCHOOL;
            target.APPCOMPLETE = source.APPCOMPLETE;
            target.SATRADMISSIONSSCORE = source.SATRADMISSIONSSCORE;
            target.SATRHIGHESTVERIFIEDMAXERW = source.SATRHIGHESTVERIFIEDMAXERW;
            target.SATRHIGHESTVERIFIEDMAXMATH = source.SATRHIGHESTVERIFIEDMAXMATH;
            target.ACTADMISSIONSSCORE = source.ACTADMISSIONSSCORE;
            target.ACTHIGHESTVERIFIEDTOTALENGLISH = source.ACTHIGHESTVERIFIEDTOTALENGLISH;
            target.ACTHIGHESTVERIFIEDTOTALMATH = source.ACTHIGHESTVERIFIEDTOTALMATH;
            target.RIC = source.RIC;
            target.ERIC = source.ERIC;
            target.HSGPACALCULATED = source.HSGPACALCULATED;
            target.LATESTEVAL = source.LATESTEVAL;
            target.EVALUATIONSTATUS = source.EVALUATIONSTATUS;
            target.EVALSTATUSDESCR = source.EVALSTATUSDESCR;
            target.AR = source.AR;
            target.ARVAL = source.ARVAL;
            target.PR = source.PR;
            target.PRVAL = source.PRVAL;
            target.SF = source.SF;
            target.SFVAL = source.SFVAL;
            target.OVR = source.OVR;
            target.OVRVAL = source.OVRVAL;
            target.WAITLISTACTIVEDATE = source.WAITLISTACTIVEDATE;
            target.WLSTRONG = source.WLSTRONG;
            target.WLSTRONGDATE = source.WLSTRONGDATE;
            target.WAITLISTCHALLENGE1 = source.WAITLISTCHALLENGE1;
            target.WAITLISTCHALLENGE2 = source.WAITLISTCHALLENGE2;
            target.WAITLISTCHALLENGE3 = source.WAITLISTCHALLENGE3;
            target.WAITLISTCHALLENGE4 = source.WAITLISTCHALLENGE4;
            target.WAITLISTCHALLENGE5 = source.WAITLISTCHALLENGE5;
            target.WAITLISTCHALLENGE6 = source.WAITLISTCHALLENGE6;
            target.WAITLISTCHALLENGE7 = source.WAITLISTCHALLENGE7;
            target.WAITLISTCHALLENGE8 = source.WAITLISTCHALLENGE8;
            target.WAITLISTCHALLENGE9 = source.WAITLISTCHALLENGE9;
            target.WAITLISTPREOFFER = source.WAITLISTPREOFFER;
            target.WAITLISTPREOFFERRESPONSE = source.WAITLISTPREOFFERRESPONSE;
            target.EVER4YR = source.EVER4YR;
            target.MULTIPLECOLLEGES = source.MULTIPLECOLLEGES;
            target.NUMBERCOLLEGES = source.NUMBERCOLLEGES;
            target.HSGRADYR = source.HSGRADYR;
            target.CURRENTCOLLINTL = source.CURRENTCOLLINTL;
            target.COLLEGECREDITS = source.COLLEGECREDITS;
            target.SCHOOL1HOURS = source.SCHOOL1HOURS;
            target.HOURSTYPE1 = source.HOURSTYPE1;
            target.SCHOOL2HOURS = source.SCHOOL2HOURS;
            target.HOURSTYPE2 = source.HOURSTYPE2;
            target.SCHOOL3HOURS = source.SCHOOL3HOURS;
            target.HOURSTYPE3 = source.HOURSTYPE3;
            target.SCHOOL4HOURS = source.SCHOOL4HOURS;
            target.HOURSTYPE4 = source.HOURSTYPE4;
            target.UWCSCHOOL = source.UWCSCHOOL;
            target.TITLEONESCHOOL = source.TITLEONESCHOOL;
            target.WAITLISTSTRONGNUMBER = source.WAITLISTSTRONGNUMBER;
            target.LC = source.LC;
            target.LCVAL = source.LCVAL;
            target.CS = source.CS;
            target.CSVAL = source.CSVAL;
            target.UB = source.UB;
            target.UBVAL = source.UBVAL;
            target.DG = source.DG;
            target.HSR = source.HSR;
            target.FOCUSSCHOOL = source.FOCUSSCHOOL;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.VwCombinedAppPool ToEntity(this VwCombinedAppPoolDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.VwCombinedAppPool();

            // Properties
            target.APPLICATIONID = source.APPLICATIONID;
            target.PERSONID = source.PERSONID;
            target.SLATEREFID = source.SLATEREFID;
            target.EMPLID = source.EMPLID;
            target.PSADMAPPLNBR = source.PSADMAPPLNBR;
            target.FIRSTNAME = source.FIRSTNAME;
            target.MIDDLENAME = source.MIDDLENAME;
            target.LASTNAME = source.LASTNAME;
            target.SEX = source.SEX;
            target.DOB = source.DOB;
            target.SOC = source.SOC;
            target.IPEDSETHNICCODE = source.IPEDSETHNICCODE;
            target.CITIZENSHIPSTATUS = source.CITIZENSHIPSTATUS;
            target.PRIMARYCITIZENSHIPCOUNTRY = source.PRIMARYCITIZENSHIPCOUNTRY;
            target.SECONDARYCITIZENSHIPCOUNTRY = source.SECONDARYCITIZENSHIPCOUNTRY;
            target.ROUNDKEY = source.ROUNDKEY;
            target.ADMITTYPE = source.ADMITTYPE;
            target.DECISIONCONFIRMEDDESCR = source.DECISIONCONFIRMEDDESCR;
            target.DECISIONCONFIRMEDREASONDESCR = source.DECISIONCONFIRMEDREASONDESCR;
            target.DECISIONCONFIRMEDCODE = source.DECISIONCONFIRMEDCODE;
            target.DECISIONCONFIRMEDREASONEXPORTKEY = source.DECISIONCONFIRMEDREASONEXPORTKEY;
            target.APPLICATIONADMITTERM = source.APPLICATIONADMITTERM;
            target.OUAGEOMARKET = source.OUAGEOMARKET;
            target.OUAREGION = source.OUAREGION;
            target.HSNAME = source.HSNAME;
            target.STAFFASSIGNED = source.STAFFASSIGNED;
            target.ETSCODE = source.ETSCODE;
            target.HSSTATE = source.HSSTATE;
            target.HSRATING = source.HSRATING;
            target.SCHOOLOFCHOICE1 = source.SCHOOLOFCHOICE1;
            target.SCHOOLOFCHOICE1DESCR = source.SCHOOLOFCHOICE1DESCR;
            target.SCHOOL1MAJOR1 = source.SCHOOL1MAJOR1;
            target.SCHOOL1MAJOR1DESCR = source.SCHOOL1MAJOR1DESCR;
            target.GPCMAJOR = source.GPCMAJOR;
            target.FINANCIALAIDINTEREST = source.FINANCIALAIDINTEREST;
            target.PELLELIGIBLE = source.PELLELIGIBLE;
            target.FACSTAFF = source.FACSTAFF;
            target.LEGACY = source.LEGACY;
            target.GIASTATUS = source.GIASTATUS;
            target.FIRSTGEN = source.FIRSTGEN;
            target.POSSE = source.POSSE;
            target.CHICAGOSCHOLAR = source.CHICAGOSCHOLAR;
            target.QUESTBRIDGE = source.QUESTBRIDGE;
            target.MOSAIC = source.MOSAIC;
            target.SCHFREEZE = source.SCHFREEZE;
            target.CORNELIUSVANDERBILTAPPLIED = source.CORNELIUSVANDERBILTAPPLIED;
            target.INGRAMAPPLIED = source.INGRAMAPPLIED;
            target.CHANCELLORSAPPLIED = source.CHANCELLORSAPPLIED;
            target.APPLICATIONUPDATE = source.APPLICATIONUPDATE;
            target.PERSONUPDATE = source.PERSONUPDATE;
            target.DECISIONUPDATE = source.DECISIONUPDATE;
            target.ACTUPDATE = source.ACTUPDATE;
            target.SCHOOLUPDATE = source.SCHOOLUPDATE;
            target.LANDSCAPEHSNEIGHBORHOOD = source.LANDSCAPEHSNEIGHBORHOOD;
            target.LANDSCAPESTDNTNEIGHBORHOOD = source.LANDSCAPESTDNTNEIGHBORHOOD;
            target.SUBMITTINGTESTING = source.SUBMITTINGTESTING;
            target.COURSEWORKRIGOR = source.COURSEWORKRIGOR;
            target.RURALHS = source.RURALHS;
            target.DACAUNDOCUMENTED = source.DACAUNDOCUMENTED;
            target.KIPP = source.KIPP;
            target.NATLMERITAWARD = source.NATLMERITAWARD;
            target.CGRADEHS = source.CGRADEHS;
            target.CGRADECOL = source.CGRADECOL;
            target.INSTITUTIONALNEED = source.INSTITUTIONALNEED;
            target.ORIGINALROUNDAPPLIED = source.ORIGINALROUNDAPPLIED;
            target.CHDIVERSITY = source.CHDIVERSITY;
            target.CHBRIDGINGGAPS = source.CHBRIDGINGGAPS;
            target.CHLEADERSHIP = source.CHLEADERSHIP;
            target.CHOVERALL = source.CHOVERALL;
            target.WAITLISTLETTER = source.WAITLISTLETTER;
            target.INTLHIGHSCHOOL = source.INTLHIGHSCHOOL;
            target.APPCOMPLETE = source.APPCOMPLETE;
            target.SATRADMISSIONSSCORE = source.SATRADMISSIONSSCORE;
            target.SATRHIGHESTVERIFIEDMAXERW = source.SATRHIGHESTVERIFIEDMAXERW;
            target.SATRHIGHESTVERIFIEDMAXMATH = source.SATRHIGHESTVERIFIEDMAXMATH;
            target.ACTADMISSIONSSCORE = source.ACTADMISSIONSSCORE;
            target.ACTHIGHESTVERIFIEDTOTALENGLISH = source.ACTHIGHESTVERIFIEDTOTALENGLISH;
            target.ACTHIGHESTVERIFIEDTOTALMATH = source.ACTHIGHESTVERIFIEDTOTALMATH;
            target.RIC = source.RIC;
            target.ERIC = source.ERIC;
            target.HSGPACALCULATED = source.HSGPACALCULATED;
            target.LATESTEVAL = source.LATESTEVAL;
            target.EVALUATIONSTATUS = source.EVALUATIONSTATUS;
            target.EVALSTATUSDESCR = source.EVALSTATUSDESCR;
            target.AR = source.AR;
            target.ARVAL = source.ARVAL;
            target.PR = source.PR;
            target.PRVAL = source.PRVAL;
            target.SF = source.SF;
            target.SFVAL = source.SFVAL;
            target.OVR = source.OVR;
            target.OVRVAL = source.OVRVAL;
            target.WAITLISTACTIVEDATE = source.WAITLISTACTIVEDATE;
            target.WLSTRONG = source.WLSTRONG;
            target.WLSTRONGDATE = source.WLSTRONGDATE;
            target.WAITLISTCHALLENGE1 = source.WAITLISTCHALLENGE1;
            target.WAITLISTCHALLENGE2 = source.WAITLISTCHALLENGE2;
            target.WAITLISTCHALLENGE3 = source.WAITLISTCHALLENGE3;
            target.WAITLISTCHALLENGE4 = source.WAITLISTCHALLENGE4;
            target.WAITLISTCHALLENGE5 = source.WAITLISTCHALLENGE5;
            target.WAITLISTCHALLENGE6 = source.WAITLISTCHALLENGE6;
            target.WAITLISTCHALLENGE7 = source.WAITLISTCHALLENGE7;
            target.WAITLISTCHALLENGE8 = source.WAITLISTCHALLENGE8;
            target.WAITLISTCHALLENGE9 = source.WAITLISTCHALLENGE9;
            target.WAITLISTPREOFFER = source.WAITLISTPREOFFER;
            target.WAITLISTPREOFFERRESPONSE = source.WAITLISTPREOFFERRESPONSE;
            target.EVER4YR = source.EVER4YR;
            target.MULTIPLECOLLEGES = source.MULTIPLECOLLEGES;
            target.NUMBERCOLLEGES = source.NUMBERCOLLEGES;
            target.HSGRADYR = source.HSGRADYR;
            target.CURRENTCOLLINTL = source.CURRENTCOLLINTL;
            target.COLLEGECREDITS = source.COLLEGECREDITS;
            target.SCHOOL1HOURS = source.SCHOOL1HOURS;
            target.HOURSTYPE1 = source.HOURSTYPE1;
            target.SCHOOL2HOURS = source.SCHOOL2HOURS;
            target.HOURSTYPE2 = source.HOURSTYPE2;
            target.SCHOOL3HOURS = source.SCHOOL3HOURS;
            target.HOURSTYPE3 = source.HOURSTYPE3;
            target.SCHOOL4HOURS = source.SCHOOL4HOURS;
            target.HOURSTYPE4 = source.HOURSTYPE4;
            target.UWCSCHOOL = source.UWCSCHOOL;
            target.TITLEONESCHOOL = source.TITLEONESCHOOL;
            target.WAITLISTSTRONGNUMBER = source.WAITLISTSTRONGNUMBER;
            target.LC = source.LC;
            target.LCVAL = source.LCVAL;
            target.CS = source.CS;
            target.CSVAL = source.CSVAL;
            target.UB = source.UB;
            target.UBVAL = source.UBVAL;
            target.DG = source.DG;
            target.HSR = source.HSR;
            target.FOCUSSCHOOL = source.FOCUSSCHOOL;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<VwCombinedAppPoolDto> ToDtos(this IEnumerable<Sam.DataModel.VwCombinedAppPool> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<VwCombinedAppPoolDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.VwCombinedAppPool> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.VwCombinedAppPool> ToEntities(this IEnumerable<VwCombinedAppPoolDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.VwCombinedAppPool source, VwCombinedAppPoolDto target);

        static partial void OnEntityCreating(VwCombinedAppPoolDto source, Sam.DataModel.VwCombinedAppPool target);

    }

}
