//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class VwDropdownAttributeGridConverter
    {

        public static VwDropdownAttributeGridDto ToDto(this Sam.DataModel.VwDropdownAttributeGrid source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static VwDropdownAttributeGridDto ToDtoWithRelated(this Sam.DataModel.VwDropdownAttributeGrid source, int level)
        {
            if (source == null)
              return null;

            var target = new VwDropdownAttributeGridDto();

            // Properties
            target.AttributeId = source.AttributeId;
            target.AttributeName = source.AttributeName;
            target.DateCreated = source.DateCreated;
            target.CreatedByUserId = source.CreatedByUserId;
            target.CreatedByUserName = source.CreatedByUserName;
            target.CreatedByUserEmail = source.CreatedByUserEmail;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.VwDropdownAttributeGrid ToEntity(this VwDropdownAttributeGridDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.VwDropdownAttributeGrid();

            // Properties
            target.AttributeId = source.AttributeId;
            target.AttributeName = source.AttributeName;
            target.DateCreated = source.DateCreated;
            target.CreatedByUserId = source.CreatedByUserId;
            target.CreatedByUserName = source.CreatedByUserName;
            target.CreatedByUserEmail = source.CreatedByUserEmail;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<VwDropdownAttributeGridDto> ToDtos(this IEnumerable<Sam.DataModel.VwDropdownAttributeGrid> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<VwDropdownAttributeGridDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.VwDropdownAttributeGrid> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.VwDropdownAttributeGrid> ToEntities(this IEnumerable<VwDropdownAttributeGridDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.VwDropdownAttributeGrid source, VwDropdownAttributeGridDto target);

        static partial void OnEntityCreating(VwDropdownAttributeGridDto source, Sam.DataModel.VwDropdownAttributeGrid target);

    }

}
