//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class VwDropdownAttributeGridDto
    {
        #region Constructors

        public VwDropdownAttributeGridDto() {
        }

        public VwDropdownAttributeGridDto(int attributeId, string attributeName, DateTime? dateCreated, int? createdByUserId, string createdByUserName, string createdByUserEmail) {

          this.AttributeId = attributeId;
          this.AttributeName = attributeName;
          this.DateCreated = dateCreated;
          this.CreatedByUserId = createdByUserId;
          this.CreatedByUserName = createdByUserName;
          this.CreatedByUserEmail = createdByUserEmail;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int AttributeId { get; set; }

        [StringLength(128)]
        [Required()]
        public string AttributeName { get; set; }

        public DateTime? DateCreated { get; set; }

        public int? CreatedByUserId { get; set; }

        [StringLength(129)]
        public string CreatedByUserName { get; set; }

        [StringLength(257)]
        public string CreatedByUserEmail { get; set; }

        #endregion
    }

}
