//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class VwHighSchoolConverter
    {

        public static VwHighSchoolDto ToDto(this Sam.DataModel.VwHighSchool source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static VwHighSchoolDto ToDtoWithRelated(this Sam.DataModel.VwHighSchool source, int level)
        {
            if (source == null)
              return null;

            var target = new VwHighSchoolDto();

            // Properties
            target.Code = source.Code;
            target.State = source.State;
            target.Name = source.Name;
            target.Rating = source.Rating;
            target.Region = source.Region;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.VwHighSchool ToEntity(this VwHighSchoolDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.VwHighSchool();

            // Properties
            target.Code = source.Code;
            target.State = source.State;
            target.Name = source.Name;
            target.Rating = source.Rating;
            target.Region = source.Region;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<VwHighSchoolDto> ToDtos(this IEnumerable<Sam.DataModel.VwHighSchool> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<VwHighSchoolDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.VwHighSchool> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.VwHighSchool> ToEntities(this IEnumerable<VwHighSchoolDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.VwHighSchool source, VwHighSchoolDto target);

        static partial void OnEntityCreating(VwHighSchoolDto source, Sam.DataModel.VwHighSchool target);

    }

}
