//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class VwHighSchoolDto
    {
        #region Constructors

        public VwHighSchoolDto() {
        }

        public VwHighSchoolDto(string code, string state, string name, string rating, string region) {

          this.Code = code;
          this.State = state;
          this.Name = name;
          this.Rating = rating;
          this.Region = region;
        }

        #endregion

        #region Properties

        [Key]
        [StringLength(16)]
        [Required()]
        public string Code { get; set; }

        [StringLength(128)]
        public string State { get; set; }

        [StringLength(256)]
        public string Name { get; set; }

        [StringLength(4)]
        public string Rating { get; set; }

        [StringLength(256)]
        public string Region { get; set; }

        #endregion
    }

}
