//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class VwListAttributeViewDto
    {
        #region Constructors

        public VwListAttributeViewDto() {
        }

        public VwListAttributeViewDto(string uniqueId, string compositeId, int listId, string listName, Guid applicationId, Guid personId, int attributeId, string attributeName, int? attributeCreatedByUserId, string attributeCreatedByFirstName, string attributeCreatedByLastName, DateTime? attributeCreatedDate, int lastModifiedByUserId, string lastModifiedByFirstName, string lastModifiedByLastName, DateTime lastModifiedDate, int? countUsageInList, int? countTotalUsage, string applicantFirstName, string applicantLastName) {

          this.UniqueId = uniqueId;
          this.CompositeId = compositeId;
          this.ListId = listId;
          this.ListName = listName;
          this.ApplicationId = applicationId;
          this.PersonId = personId;
          this.AttributeId = attributeId;
          this.AttributeName = attributeName;
          this.AttributeCreatedByUserId = attributeCreatedByUserId;
          this.AttributeCreatedByFirstName = attributeCreatedByFirstName;
          this.AttributeCreatedByLastName = attributeCreatedByLastName;
          this.AttributeCreatedDate = attributeCreatedDate;
          this.LastModifiedByUserId = lastModifiedByUserId;
          this.LastModifiedByFirstName = lastModifiedByFirstName;
          this.LastModifiedByLastName = lastModifiedByLastName;
          this.LastModifiedDate = lastModifiedDate;
          this.CountUsageInList = countUsageInList;
          this.CountTotalUsage = countTotalUsage;
          this.ApplicantFirstName = applicantFirstName;
          this.ApplicantLastName = applicantLastName;
        }

        #endregion

        #region Properties

        [Key]
        [StringLength(95)]
        [Required()]
        public string UniqueId { get; set; }

        [StringLength(84)]
        public string CompositeId { get; set; }

        [Required()]
        public int ListId { get; set; }

        [StringLength(64)]
        [Required()]
        public string ListName { get; set; }

        [Required()]
        public Guid ApplicationId { get; set; }

        [Required()]
        public Guid PersonId { get; set; }

        [Required()]
        public int AttributeId { get; set; }

        [StringLength(128)]
        [Required()]
        public string AttributeName { get; set; }

        public int? AttributeCreatedByUserId { get; set; }

        [StringLength(64)]
        [Required()]
        public string AttributeCreatedByFirstName { get; set; }

        [StringLength(64)]
        [Required()]
        public string AttributeCreatedByLastName { get; set; }

        public DateTime? AttributeCreatedDate { get; set; }

        [Required()]
        public int LastModifiedByUserId { get; set; }

        [StringLength(64)]
        [Required()]
        public string LastModifiedByFirstName { get; set; }

        [StringLength(64)]
        [Required()]
        public string LastModifiedByLastName { get; set; }

        [Required()]
        public DateTime LastModifiedDate { get; set; }

        public int? CountUsageInList { get; set; }

        public int? CountTotalUsage { get; set; }

        [StringLength(64)]
        public string ApplicantFirstName { get; set; }

        [StringLength(64)]
        public string ApplicantLastName { get; set; }

        #endregion
    }

}
