//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class VwListAttributeViewConverter
    {

        public static VwListAttributeViewDto ToDto(this Sam.DataModel.VwListAttributeView source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static VwListAttributeViewDto ToDtoWithRelated(this Sam.DataModel.VwListAttributeView source, int level)
        {
            if (source == null)
              return null;

            var target = new VwListAttributeViewDto();

            // Properties
            target.UniqueId = source.UniqueId;
            target.CompositeId = source.CompositeId;
            target.ListId = source.ListId;
            target.ListName = source.ListName;
            target.ApplicationId = source.ApplicationId;
            target.PersonId = source.PersonId;
            target.AttributeId = source.AttributeId;
            target.AttributeName = source.AttributeName;
            target.AttributeCreatedByUserId = source.AttributeCreatedByUserId;
            target.AttributeCreatedByFirstName = source.AttributeCreatedByFirstName;
            target.AttributeCreatedByLastName = source.AttributeCreatedByLastName;
            target.AttributeCreatedDate = source.AttributeCreatedDate;
            target.LastModifiedByUserId = source.LastModifiedByUserId;
            target.LastModifiedByFirstName = source.LastModifiedByFirstName;
            target.LastModifiedByLastName = source.LastModifiedByLastName;
            target.LastModifiedDate = source.LastModifiedDate;
            target.CountUsageInList = source.CountUsageInList;
            target.CountTotalUsage = source.CountTotalUsage;
            target.ApplicantFirstName = source.ApplicantFirstName;
            target.ApplicantLastName = source.ApplicantLastName;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.VwListAttributeView ToEntity(this VwListAttributeViewDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.VwListAttributeView();

            // Properties
            target.UniqueId = source.UniqueId;
            target.CompositeId = source.CompositeId;
            target.ListId = source.ListId;
            target.ListName = source.ListName;
            target.ApplicationId = source.ApplicationId;
            target.PersonId = source.PersonId;
            target.AttributeId = source.AttributeId;
            target.AttributeName = source.AttributeName;
            target.AttributeCreatedByUserId = source.AttributeCreatedByUserId;
            target.AttributeCreatedByFirstName = source.AttributeCreatedByFirstName;
            target.AttributeCreatedByLastName = source.AttributeCreatedByLastName;
            target.AttributeCreatedDate = source.AttributeCreatedDate;
            target.LastModifiedByUserId = source.LastModifiedByUserId;
            target.LastModifiedByFirstName = source.LastModifiedByFirstName;
            target.LastModifiedByLastName = source.LastModifiedByLastName;
            target.LastModifiedDate = source.LastModifiedDate;
            target.CountUsageInList = source.CountUsageInList;
            target.CountTotalUsage = source.CountTotalUsage;
            target.ApplicantFirstName = source.ApplicantFirstName;
            target.ApplicantLastName = source.ApplicantLastName;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<VwListAttributeViewDto> ToDtos(this IEnumerable<Sam.DataModel.VwListAttributeView> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<VwListAttributeViewDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.VwListAttributeView> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.VwListAttributeView> ToEntities(this IEnumerable<VwListAttributeViewDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.VwListAttributeView source, VwListAttributeViewDto target);

        static partial void OnEntityCreating(VwListAttributeViewDto source, Sam.DataModel.VwListAttributeView target);

    }

}
