//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace Sam.DataTransferObjects
{

    public partial class VwListAttributeViewGridDto
    {
        #region Constructors

        public VwListAttributeViewGridDto() {
        }

        public VwListAttributeViewGridDto(string uniqueId, string compositeId, int attributeId, string attributeName) {

          this.UniqueId = uniqueId;
          this.CompositeId = compositeId;
          this.AttributeId = attributeId;
          this.AttributeName = attributeName;
        }

        #endregion

        #region Properties

        [Key]
        [StringLength(95)]
        [Required()]
        public string UniqueId { get; set; }

        [StringLength(84)]
        public string CompositeId { get; set; }

        [Required()]
        public int AttributeId { get; set; }

        [StringLength(128)]
        [Required()]
        public string AttributeName { get; set; }

        #endregion
    }

}
