//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Sam DTO
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Sam.DataTransferObjects
{

    public static partial class VwListAttributeViewGridConverter
    {

        public static VwListAttributeViewGridDto ToDto(this Sam.DataModel.VwListAttributeViewGrid source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static VwListAttributeViewGridDto ToDtoWithRelated(this Sam.DataModel.VwListAttributeViewGrid source, int level)
        {
            if (source == null)
              return null;

            var target = new VwListAttributeViewGridDto();

            // Properties
            target.UniqueId = source.UniqueId;
            target.CompositeId = source.CompositeId;
            target.AttributeId = source.AttributeId;
            target.AttributeName = source.AttributeName;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Sam.DataModel.VwListAttributeViewGrid ToEntity(this VwListAttributeViewGridDto source)
        {
            if (source == null)
              return null;

            var target = new Sam.DataModel.VwListAttributeViewGrid();

            // Properties
            target.UniqueId = source.UniqueId;
            target.CompositeId = source.CompositeId;
            target.AttributeId = source.AttributeId;
            target.AttributeName = source.AttributeName;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<VwListAttributeViewGridDto> ToDtos(this IEnumerable<Sam.DataModel.VwListAttributeViewGrid> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<VwListAttributeViewGridDto> ToDtosWithRelated(this IEnumerable<Sam.DataModel.VwListAttributeViewGrid> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Sam.DataModel.VwListAttributeViewGrid> ToEntities(this IEnumerable<VwListAttributeViewGridDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Sam.DataModel.VwListAttributeViewGrid source, VwListAttributeViewGridDto target);

        static partial void OnEntityCreating(VwListAttributeViewGridDto source, Sam.DataModel.VwListAttributeViewGrid target);

    }

}
