//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class Application : ICloneable {

        public Application()
        {
            this.IsDacaUndocumented = false;
            this.IsAttendingRuralHs = false;
            this.IsAttendingKippSchool = false;
            this.CorneliusVanderbiltScholarship = false;
            this.IngramScholarship = false;
            this.ChancellorScholarship = false;
            this.ListAttributes = new List<ListAttribute>();
            this.AuditLog = new List<AuditLog>();
            OnCreated();
        }

        public virtual Guid ApplicationId { get; set; }

        public virtual int ListId { get; set; }

        public virtual Guid PersonId { get; set; }

        public virtual DateTime? ApplicationUpdate { get; set; }

        public virtual string PsAdmApplNbr { get; set; }

        public virtual string Career { get; set; }

        public virtual string RoundKey { get; set; }

        public virtual string AdmitType { get; set; }

        public virtual string ApplicationAdmitTerm { get; set; }

        public virtual int? SatAdmissionsScore { get; set; }

        public virtual string TestType { get; set; }

        public virtual DateTime? TestUpdate { get; set; }

        public virtual int? SatHighestVerifiedMaxCriticalReading { get; set; }

        public virtual int? SatHighestVerifiedMaxMath { get; set; }

        public virtual int? SatrAdmissionsScore { get; set; }

        public virtual int? SatrHighestVerifiedMaxErw { get; set; }

        public virtual int? SatrHighestVerifiedMaxMath { get; set; }

        public virtual int? ActHighestVerifiedTotalEnglish { get; set; }

        public virtual int? ActHighestVerifiedTotalMath { get; set; }

        public virtual decimal? RIC { get; set; }

        public virtual decimal? ERIC { get; set; }

        public virtual DateTime? DecisionUpdate { get; set; }

        public virtual string DecisionConfirmedDescription { get; set; }

        public virtual string DecisionConfirmedExport3Code { get; set; }

        public virtual string DecisionConfirmedCode { get; set; }

        public virtual string DecisionConfirmedReasonDescription { get; set; }

        public virtual string DecisionConfirmedReasonExportKey { get; set; }

        public virtual DateTime? SchoolUpdate { get; set; }

        public virtual decimal? HsgpaCalculated { get; set; }

        public virtual string LatestEvaluation { get; set; }

        public virtual string EvaluationStatus { get; set; }

        public virtual string EvalStatusDescr { get; set; }

        public virtual string Ar { get; set; }

        public virtual int? ArVal { get; set; }

        public virtual string Pr { get; set; }

        public virtual int? PrVal { get; set; }

        public virtual string Sf { get; set; }

        public virtual int? SfVal { get; set; }

        public virtual string Ovr { get; set; }

        public virtual int? OvrVal { get; set; }

        public virtual string OuaGeoMarket { get; set; }

        public virtual string OuaRegion { get; set; }

        public virtual string StaffAssigned { get; set; }

        public virtual string EtsCode { get; set; }

        public virtual string HsState { get; set; }

        public virtual string HsName { get; set; }

        public virtual string HsRating { get; set; }

        public virtual string SchoolOfChoice1 { get; set; }

        public virtual string SchoolOfChoice1Descr { get; set; }

        public virtual string School1Major1 { get; set; }

        public virtual string School1Major1Descr { get; set; }

        public virtual string GpcMajor { get; set; }

        public virtual bool? FinancialAidInterest { get; set; }

        public virtual bool? PellEligible { get; set; }

        public virtual string FacStaff { get; set; }

        public virtual string UCode { get; set; }

        public virtual string Legacy { get; set; }

        public virtual string GiaStatus { get; set; }

        public virtual bool? FirstGen { get; set; }

        public virtual string Posse { get; set; }

        public virtual string ChicagoScholar { get; set; }

        public virtual string QuestBridge { get; set; }

        public virtual bool? Mosaic { get; set; }

        public virtual DateTime? WaitlistActiveDate { get; set; }

        public virtual string WlStrong { get; set; }

        public virtual bool? WaitlistChallenge1 { get; set; }

        public virtual bool? WaitlistChallenge2 { get; set; }

        public virtual bool? WaitlistChallenge3 { get; set; }

        public virtual bool? WaitlistChallenge4 { get; set; }

        public virtual bool? WaitlistChallenge5 { get; set; }

        public virtual bool? WaitlistChallenge6 { get; set; }

        public virtual bool? WaitlistChallenge7 { get; set; }

        public virtual bool? WaitlistChallenge8 { get; set; }

        public virtual bool? WaitlistChallenge9 { get; set; }

        public virtual bool? WaitlistPreOffer { get; set; }

        public virtual bool? WaitlistPreOfferResponse { get; set; }

        public virtual DateTime? PersonUpdate { get; set; }

        public virtual string SlateRefId { get; set; }

        public virtual string EmplId { get; set; }

        public virtual string FirstName { get; set; }

        public virtual string LastName { get; set; }

        public virtual string MiddleName { get; set; }

        public virtual string Sex { get; set; }

        public virtual string Race { get; set; }

        public virtual string Hispanic { get; set; }

        public virtual string IpedsEthnicCode { get; set; }

        public virtual string IpedsEthnicDescr { get; set; }

        public virtual int? ProtectionId { get; set; }

        public virtual int? ActAdmissionsScore { get; set; }

        public virtual bool? SchFreeze { get; set; }

        public virtual bool? ManualFreeze { get; set; }

        public virtual bool? SOC { get; set; }

        public virtual string CitizenshipStatus { get; set; }

        public virtual string PrimaryCitizenshipCountry { get; set; }

        public virtual string SecondaryCitizenshipCountry { get; set; }

        public virtual bool Active { get; set; }

        public virtual string LandscapeLocale { get; set; }

        public virtual int? LandscapeHSNeighborhood { get; set; }

        public virtual int? LandscapeStdntNeighborhood { get; set; }

        public virtual DateTime? DateOfBirth { get; set; }

        public virtual bool? IsTestingSubmitted { get; set; }

        public virtual string CourseworkRigor { get; set; }

        public virtual bool? WasEver4Year { get; set; }

        public virtual bool? HasMultipleColleges { get; set; }

        public virtual int? NumberOfColleges { get; set; }

        public virtual string HasTakenCalculus { get; set; }

        public virtual string HasTakenPhysics { get; set; }

        public virtual string HasTakenChemistry { get; set; }

        public virtual string CurrentInternationalCollege { get; set; }

        public virtual decimal? CollegeCredits { get; set; }

        public virtual int? HighSchoolGradYear { get; set; }

        public virtual int? School1Hours { get; set; }

        public virtual int? School2Hours { get; set; }

        public virtual int? School3Hours { get; set; }

        public virtual int? School4Hours { get; set; }

        public virtual string School1HoursType { get; set; }

        public virtual string School2HoursType { get; set; }

        public virtual string School3HoursType { get; set; }

        public virtual string School4HoursType { get; set; }

        public virtual bool IsDacaUndocumented { get; set; }

        public virtual bool IsAttendingRuralHs { get; set; }

        public virtual bool IsAttendingKippSchool { get; set; }

        public virtual bool HasNationalMeritAward { get; set; }

        public virtual bool? IsCGradeCollege { get; set; }

        public virtual bool? IsCGradeHighSchool { get; set; }

        public virtual decimal? InstitutionalNeed { get; set; }

        public virtual DateTime? WaitListStrongDate { get; set; }

        public string OriginalRoundKey { get; set; }

        public bool CorneliusVanderbiltScholarship { get; set; }

        public bool IngramScholarship { get; set; }

        public bool ChancellorScholarship { get; set; }

        public string Vv { get; set; }

        public int? VvVal { get; set; }

        public int? ChDiversity { get; set; }

        public int? ChBridgingGaps { get; set; }

        public int? ChLeadership { get; set; }

        public int? ChOverall { get; set; }

        public bool? WaitlistLetter { get; set; }

        public bool? IntlHighSchool { get; set; }

        public bool? UwcSchool { get; set; }

        public bool? TitleOneSchool { get; set; }

        public int? WaitlistStrongNumber { get; set; }

        public string Cs { get; set; }

        public int? CsVal { get; set; }

        public string Lc { get; set; }

        public int? LcVal { get; set; }

        public string Ub { get; set; }

        public int? UbVal { get; set; }

        public int? DG { get; set; }

        public double? HSR { get; set; }

        public bool? AppComplete { get; set; }

        public bool? FocusSchool { get; set; }

        public virtual List List { get; set; }

        public virtual Protection Protection { get; set; }

        public virtual IList<ListAttribute> ListAttributes { get; set; }

        public virtual IList<AuditLog> AuditLog { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Application toCompare = obj as Application;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.ApplicationId, toCompare.ApplicationId))
            return false;
          if (!Object.Equals(this.ListId, toCompare.ListId))
            return false;
          if (!Object.Equals(this.PersonId, toCompare.PersonId))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + ApplicationId.GetHashCode();
          hashCode = (hashCode * 7) + ListId.GetHashCode();
          hashCode = (hashCode * 7) + PersonId.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            Application obj = new Application();
            obj.ApplicationId = ApplicationId;
            obj.ListId = ListId;
            obj.PersonId = PersonId;
            obj.ApplicationUpdate = ApplicationUpdate;
            obj.PsAdmApplNbr = PsAdmApplNbr;
            obj.Career = Career;
            obj.RoundKey = RoundKey;
            obj.AdmitType = AdmitType;
            obj.ApplicationAdmitTerm = ApplicationAdmitTerm;
            obj.SatAdmissionsScore = SatAdmissionsScore;
            obj.TestType = TestType;
            obj.TestUpdate = TestUpdate;
            obj.SatHighestVerifiedMaxCriticalReading = SatHighestVerifiedMaxCriticalReading;
            obj.SatHighestVerifiedMaxMath = SatHighestVerifiedMaxMath;
            obj.SatrAdmissionsScore = SatrAdmissionsScore;
            obj.SatrHighestVerifiedMaxErw = SatrHighestVerifiedMaxErw;
            obj.SatrHighestVerifiedMaxMath = SatrHighestVerifiedMaxMath;
            obj.ActHighestVerifiedTotalEnglish = ActHighestVerifiedTotalEnglish;
            obj.ActHighestVerifiedTotalMath = ActHighestVerifiedTotalMath;
            obj.RIC = RIC;
            obj.ERIC = ERIC;
            obj.DecisionUpdate = DecisionUpdate;
            obj.DecisionConfirmedDescription = DecisionConfirmedDescription;
            obj.DecisionConfirmedExport3Code = DecisionConfirmedExport3Code;
            obj.DecisionConfirmedCode = DecisionConfirmedCode;
            obj.DecisionConfirmedReasonDescription = DecisionConfirmedReasonDescription;
            obj.DecisionConfirmedReasonExportKey = DecisionConfirmedReasonExportKey;
            obj.SchoolUpdate = SchoolUpdate;
            obj.HsgpaCalculated = HsgpaCalculated;
            obj.LatestEvaluation = LatestEvaluation;
            obj.EvaluationStatus = EvaluationStatus;
            obj.EvalStatusDescr = EvalStatusDescr;
            obj.Ar = Ar;
            obj.ArVal = ArVal;
            obj.Pr = Pr;
            obj.PrVal = PrVal;
            obj.Sf = Sf;
            obj.SfVal = SfVal;
            obj.Ovr = Ovr;
            obj.OvrVal = OvrVal;
            obj.OuaGeoMarket = OuaGeoMarket;
            obj.OuaRegion = OuaRegion;
            obj.StaffAssigned = StaffAssigned;
            obj.EtsCode = EtsCode;
            obj.HsState = HsState;
            obj.HsName = HsName;
            obj.HsRating = HsRating;
            obj.SchoolOfChoice1 = SchoolOfChoice1;
            obj.SchoolOfChoice1Descr = SchoolOfChoice1Descr;
            obj.School1Major1 = School1Major1;
            obj.School1Major1Descr = School1Major1Descr;
            obj.GpcMajor = GpcMajor;
            obj.FinancialAidInterest = FinancialAidInterest;
            obj.PellEligible = PellEligible;
            obj.FacStaff = FacStaff;
            obj.UCode = UCode;
            obj.Legacy = Legacy;
            obj.GiaStatus = GiaStatus;
            obj.FirstGen = FirstGen;
            obj.Posse = Posse;
            obj.ChicagoScholar = ChicagoScholar;
            obj.QuestBridge = QuestBridge;
            obj.Mosaic = Mosaic;
            obj.WaitlistActiveDate = WaitlistActiveDate;
            obj.WlStrong = WlStrong;
            obj.WaitlistChallenge1 = WaitlistChallenge1;
            obj.WaitlistChallenge2 = WaitlistChallenge2;
            obj.WaitlistChallenge3 = WaitlistChallenge3;
            obj.WaitlistChallenge4 = WaitlistChallenge4;
            obj.WaitlistChallenge5 = WaitlistChallenge5;
            obj.WaitlistChallenge6 = WaitlistChallenge6;
            obj.WaitlistChallenge7 = WaitlistChallenge7;
            obj.WaitlistChallenge8 = WaitlistChallenge8;
            obj.WaitlistChallenge9 = WaitlistChallenge9;
            obj.WaitlistPreOffer = WaitlistPreOffer;
            obj.WaitlistPreOfferResponse = WaitlistPreOfferResponse;
            obj.PersonUpdate = PersonUpdate;
            obj.SlateRefId = SlateRefId;
            obj.EmplId = EmplId;
            obj.FirstName = FirstName;
            obj.LastName = LastName;
            obj.MiddleName = MiddleName;
            obj.Sex = Sex;
            obj.Race = Race;
            obj.Hispanic = Hispanic;
            obj.IpedsEthnicCode = IpedsEthnicCode;
            obj.IpedsEthnicDescr = IpedsEthnicDescr;
            obj.ProtectionId = ProtectionId;
            obj.ActAdmissionsScore = ActAdmissionsScore;
            obj.SchFreeze = SchFreeze;
            obj.ManualFreeze = ManualFreeze;
            obj.SOC = SOC;
            obj.CitizenshipStatus = CitizenshipStatus;
            obj.PrimaryCitizenshipCountry = PrimaryCitizenshipCountry;
            obj.SecondaryCitizenshipCountry = SecondaryCitizenshipCountry;
            obj.Active = Active;
            obj.LandscapeLocale = LandscapeLocale;
            obj.LandscapeHSNeighborhood = LandscapeHSNeighborhood;
            obj.LandscapeStdntNeighborhood = LandscapeStdntNeighborhood;
            obj.DateOfBirth = DateOfBirth;
            obj.IsTestingSubmitted = IsTestingSubmitted;
            obj.CourseworkRigor = CourseworkRigor;
            obj.WasEver4Year = WasEver4Year;
            obj.HasMultipleColleges = HasMultipleColleges;
            obj.NumberOfColleges = NumberOfColleges;
            obj.HasTakenCalculus = HasTakenCalculus;
            obj.HasTakenPhysics = HasTakenPhysics;
            obj.HasTakenChemistry = HasTakenChemistry;
            obj.CurrentInternationalCollege = CurrentInternationalCollege;
            obj.CollegeCredits = CollegeCredits;
            obj.HighSchoolGradYear = HighSchoolGradYear;
            obj.School1Hours = School1Hours;
            obj.School2Hours = School2Hours;
            obj.School3Hours = School3Hours;
            obj.School4Hours = School4Hours;
            obj.School1HoursType = School1HoursType;
            obj.School2HoursType = School2HoursType;
            obj.School3HoursType = School3HoursType;
            obj.School4HoursType = School4HoursType;
            obj.IsDacaUndocumented = IsDacaUndocumented;
            obj.IsAttendingRuralHs = IsAttendingRuralHs;
            obj.IsAttendingKippSchool = IsAttendingKippSchool;
            obj.HasNationalMeritAward = HasNationalMeritAward;
            obj.IsCGradeCollege = IsCGradeCollege;
            obj.IsCGradeHighSchool = IsCGradeHighSchool;
            obj.InstitutionalNeed = InstitutionalNeed;
            obj.WaitListStrongDate = WaitListStrongDate;
            obj.OriginalRoundKey = OriginalRoundKey;
            obj.CorneliusVanderbiltScholarship = CorneliusVanderbiltScholarship;
            obj.IngramScholarship = IngramScholarship;
            obj.ChancellorScholarship = ChancellorScholarship;
            obj.Vv = Vv;
            obj.VvVal = VvVal;
            obj.ChDiversity = ChDiversity;
            obj.ChBridgingGaps = ChBridgingGaps;
            obj.ChLeadership = ChLeadership;
            obj.ChOverall = ChOverall;
            obj.WaitlistLetter = WaitlistLetter;
            obj.IntlHighSchool = IntlHighSchool;
            obj.UwcSchool = UwcSchool;
            obj.TitleOneSchool = TitleOneSchool;
            obj.WaitlistStrongNumber = WaitlistStrongNumber;
            obj.Cs = Cs;
            obj.CsVal = CsVal;
            obj.Lc = Lc;
            obj.LcVal = LcVal;
            obj.Ub = Ub;
            obj.UbVal = UbVal;
            obj.DG = DG;
            obj.HSR = HSR;
            obj.AppComplete = AppComplete;
            obj.FocusSchool = FocusSchool;
            return obj;
        }

        #endregion
    }

}
