//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class AuditLog : ICloneable {

        public AuditLog()
        {
            OnCreated();
        }

        public long Id { get; set; }

        public int ListId { get; set; }

        public Guid ApplicationId { get; set; }

        public Guid PersonId { get; set; }

        public int UserId { get; set; }

        public DateTime LogDate { get; set; }

        public int? ProtectionId { get; set; }

        public int? CustomAttributeId { get; set; }

        public string Action { get; set; }

        public virtual Application Application { get; set; }

        public virtual Protection Protection { get; set; }

        public virtual CustomAttribute CustomAttribute { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            AuditLog obj = new AuditLog();
            obj.Id = Id;
            obj.ListId = ListId;
            obj.ApplicationId = ApplicationId;
            obj.PersonId = PersonId;
            obj.UserId = UserId;
            obj.LogDate = LogDate;
            obj.ProtectionId = ProtectionId;
            obj.CustomAttributeId = CustomAttributeId;
            obj.Action = Action;
            return obj;
        }

        #endregion
    }

}
