//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class CustomAttribute : ICloneable {

        public CustomAttribute()
        {
            this.ListAttributes = new List<ListAttribute>();
            this.AuditLogs = new List<AuditLog>();
            this.Queues = new List<Queue>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual int? CreatedByUserId { get; set; }

        public virtual DateTime? CreatedDate { get; set; }

        public DateTime? DeletedDate { get; set; }

        public virtual IList<ListAttribute> ListAttributes { get; set; }

        public virtual User User { get; set; }

        public virtual IList<AuditLog> AuditLogs { get; set; }

        public virtual IList<Queue> Queues { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CustomAttribute obj = new CustomAttribute();
            obj.Id = Id;
            obj.Name = Name;
            obj.CreatedByUserId = CreatedByUserId;
            obj.CreatedDate = CreatedDate;
            obj.DeletedDate = DeletedDate;
            return obj;
        }

        #endregion
    }

}
