//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class DropDownType : ICloneable {

        public DropDownType()
        {
            this.DropDowns = new List<DropDown>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Description { get; set; }

        public virtual IList<DropDown> DropDowns { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            DropDownType obj = new DropDownType();
            obj.Id = Id;
            obj.Name = Name;
            obj.Description = Description;
            return obj;
        }

        #endregion
    }

}
