//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class DropDown : ICloneable {

        public DropDown()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int TypeId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Description { get; set; }

        public virtual string Code { get; set; }

        public virtual string FilterValue { get; set; }

        public virtual int? Rank { get; set; }

        public virtual int? SortOrder { get; set; }

        public virtual bool Display { get; set; }

        public virtual DropDownType DropDownType { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            DropDown obj = new DropDown();
            obj.Id = Id;
            obj.TypeId = TypeId;
            obj.Name = Name;
            obj.Description = Description;
            obj.Code = Code;
            obj.FilterValue = FilterValue;
            obj.Rank = Rank;
            obj.SortOrder = SortOrder;
            obj.Display = Display;
            return obj;
        }

        #endregion
    }

}
