//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class FilterAuditLog : ICloneable {

        public FilterAuditLog()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public int ListId { get; set; }

        public int UserId { get; set; }

        public DateTime FilterDateTime { get; set; }

        public string FilterObject { get; set; }

        public virtual List List { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            FilterAuditLog obj = new FilterAuditLog();
            obj.Id = Id;
            obj.ListId = ListId;
            obj.UserId = UserId;
            obj.FilterDateTime = FilterDateTime;
            obj.FilterObject = FilterObject;
            return obj;
        }

        #endregion
    }

}
