//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class HistoricalTarget : ICloneable {

        public HistoricalTarget()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int HistoricalTargetTypeId { get; set; }

        public virtual string Cohort { get; set; }

        public virtual int? Count { get; set; }

        public virtual double? OldSAT { get; set; }

        public virtual double? NewSAT { get; set; }

        public virtual double? ACT { get; set; }

        public virtual double? RIC { get; set; }

        public virtual double? TOP10 { get; set; }

        public virtual int? TN { get; set; }

        public virtual int? NE { get; set; }

        public virtual int? MS { get; set; }

        public virtual int? SO { get; set; }

        public virtual int? MW { get; set; }

        public virtual int? SW { get; set; }

        public virtual int? WS { get; set; }

        public virtual int? Min { get; set; }

        public virtual int? I { get; set; }

        public virtual int? A { get; set; }

        public virtual int? B { get; set; }

        public virtual int? H { get; set; }

        public virtual int? P { get; set; }

        public virtual int? W { get; set; }

        public virtual int? N { get; set; }

        public virtual int? Multi { get; set; }

        public virtual int? Intl { get; set; }

        public virtual int? Male { get; set; }

        public virtual int? Female { get; set; }

        public virtual DateTime? EffectiveDate { get; set; }

        public virtual string School { get; set; }

        public virtual string Major { get; set; }

        public virtual string SchoolDivision { get; set; }

        public virtual string NotificationPlanCode { get; set; }

        public virtual string TermNotif { get; set; }

        public virtual double? IPerc { get; set; }

        public virtual double? BPerc { get; set; }

        public virtual double? HPerc { get; set; }

        public virtual double? PPerc { get; set; }

        public virtual double? WPerc { get; set; }

        public virtual int? NA { get; set; }

        public virtual double? NAPerc { get; set; }

        public virtual double? MultiPerc { get; set; }

        public virtual double? IntlPerc { get; set; }

        public virtual double? MalePerc { get; set; }

        public virtual double? FemalePerc { get; set; }

        public virtual double? APerc { get; set; }

        public virtual double? MinPerc { get; set; }

        public virtual HistoricalTargetType HistoricalTargetType { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            HistoricalTarget obj = new HistoricalTarget();
            obj.Id = Id;
            obj.HistoricalTargetTypeId = HistoricalTargetTypeId;
            obj.Cohort = Cohort;
            obj.Count = Count;
            obj.OldSAT = OldSAT;
            obj.NewSAT = NewSAT;
            obj.ACT = ACT;
            obj.RIC = RIC;
            obj.TOP10 = TOP10;
            obj.TN = TN;
            obj.NE = NE;
            obj.MS = MS;
            obj.SO = SO;
            obj.MW = MW;
            obj.SW = SW;
            obj.WS = WS;
            obj.Min = Min;
            obj.I = I;
            obj.A = A;
            obj.B = B;
            obj.H = H;
            obj.P = P;
            obj.W = W;
            obj.N = N;
            obj.Multi = Multi;
            obj.Intl = Intl;
            obj.Male = Male;
            obj.Female = Female;
            obj.EffectiveDate = EffectiveDate;
            obj.School = School;
            obj.Major = Major;
            obj.SchoolDivision = SchoolDivision;
            obj.NotificationPlanCode = NotificationPlanCode;
            obj.TermNotif = TermNotif;
            obj.IPerc = IPerc;
            obj.BPerc = BPerc;
            obj.HPerc = HPerc;
            obj.PPerc = PPerc;
            obj.WPerc = WPerc;
            obj.NA = NA;
            obj.NAPerc = NAPerc;
            obj.MultiPerc = MultiPerc;
            obj.IntlPerc = IntlPerc;
            obj.MalePerc = MalePerc;
            obj.FemalePerc = FemalePerc;
            obj.APerc = APerc;
            obj.MinPerc = MinPerc;
            return obj;
        }

        #endregion
    }

}
