//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class ImportAttrib : ICloneable {

        public ImportAttrib()
        {
            OnCreated();
        }

        public virtual long Id { get; set; }

        public virtual int UserId { get; set; }

        public virtual int ImportStateId { get; set; }

        public virtual byte[] Spreadsheet { get; set; }

        public virtual byte[] ImportLog { get; set; }

        public virtual DateTime UploadDate { get; set; }

        public virtual DateTime? ImportDate { get; set; }

        public virtual int ListId { get; set; }

        public virtual User User { get; set; }

        public virtual ImportState ImportState { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            ImportAttrib obj = new ImportAttrib();
            obj.Id = Id;
            obj.UserId = UserId;
            obj.ImportStateId = ImportStateId;
            obj.Spreadsheet = Spreadsheet;
            obj.ImportLog = ImportLog;
            obj.UploadDate = UploadDate;
            obj.ImportDate = ImportDate;
            obj.ListId = ListId;
            return obj;
        }

        #endregion
    }

}
