//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class ListAttribute : ICloneable {

        public ListAttribute()
        {
            OnCreated();
        }

        public virtual int ListId { get; set; }

        public virtual Guid ApplicationId { get; set; }

        public virtual Guid PersonId { get; set; }

        public virtual int AttributeId { get; set; }

        public virtual int LastModifyUserId { get; set; }

        public virtual DateTime LastModifyDate { get; set; }

        public virtual CustomAttribute CustomAttribute { get; set; }

        public virtual Application Application { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          ListAttribute toCompare = obj as ListAttribute;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.ListId, toCompare.ListId))
            return false;
          if (!Object.Equals(this.ApplicationId, toCompare.ApplicationId))
            return false;
          if (!Object.Equals(this.PersonId, toCompare.PersonId))
            return false;
          if (!Object.Equals(this.AttributeId, toCompare.AttributeId))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + ListId.GetHashCode();
          hashCode = (hashCode * 7) + ApplicationId.GetHashCode();
          hashCode = (hashCode * 7) + PersonId.GetHashCode();
          hashCode = (hashCode * 7) + AttributeId.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            ListAttribute obj = new ListAttribute();
            obj.ListId = ListId;
            obj.ApplicationId = ApplicationId;
            obj.PersonId = PersonId;
            obj.AttributeId = AttributeId;
            obj.LastModifyUserId = LastModifyUserId;
            obj.LastModifyDate = LastModifyDate;
            return obj;
        }

        #endregion
    }

}
