//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class ListUserRole : ICloneable {

        public ListUserRole()
        {
            OnCreated();
        }

        public virtual int ListId { get; set; }

        public virtual int UserId { get; set; }

        public virtual int ListRoleId { get; set; }

        public virtual List List { get; set; }

        public virtual ListRole ListRole { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          ListUserRole toCompare = obj as ListUserRole;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.ListId, toCompare.ListId))
            return false;
          if (!Object.Equals(this.UserId, toCompare.UserId))
            return false;
          if (!Object.Equals(this.ListRoleId, toCompare.ListRoleId))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + ListId.GetHashCode();
          hashCode = (hashCode * 7) + UserId.GetHashCode();
          hashCode = (hashCode * 7) + ListRoleId.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            ListUserRole obj = new ListUserRole();
            obj.ListId = ListId;
            obj.UserId = UserId;
            obj.ListRoleId = ListRoleId;
            return obj;
        }

        #endregion
    }

}
