//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class List : ICloneable {

        public List()
        {
            this.Applications = new List<Application>();
            this.ListUserRoles = new List<ListUserRole>();
            this.RefreshLogs = new List<RefreshLog>();
            this.FilterAuditLogs = new List<FilterAuditLog>();
            this.Queues = new List<Queue>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Cohort { get; set; }

        public virtual string StudentType { get; set; }

        public virtual DateTime CreateDate { get; set; }

        public virtual DateTime? ModifyDate { get; set; }

        public virtual DateTime? LastRefreshDate { get; set; }

        public virtual bool RefreshSuccessful { get; set; }

        public virtual bool Final { get; set; }

        public virtual IList<Application> Applications { get; set; }

        public virtual IList<ListUserRole> ListUserRoles { get; set; }

        public virtual IList<RefreshLog> RefreshLogs { get; set; }

        public virtual IList<FilterAuditLog> FilterAuditLogs { get; set; }

        public virtual IList<Queue> Queues { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            List obj = new List();
            obj.Id = Id;
            obj.Name = Name;
            obj.Cohort = Cohort;
            obj.StudentType = StudentType;
            obj.CreateDate = CreateDate;
            obj.ModifyDate = ModifyDate;
            obj.LastRefreshDate = LastRefreshDate;
            obj.RefreshSuccessful = RefreshSuccessful;
            obj.Final = Final;
            return obj;
        }

        #endregion
    }

}
