//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class Protection : ICloneable {

        public Protection()
        {
            this.AuditLogs = new List<AuditLog>();
            this.Queues = new List<Queue>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Description { get; set; }

        public virtual IList<AuditLog> AuditLogs { get; set; }

        public virtual IList<Queue> Queues { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            Protection obj = new Protection();
            obj.Id = Id;
            obj.Name = Name;
            obj.Description = Description;
            return obj;
        }

        #endregion
    }

}
