//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class Queue : ICloneable {

        public Queue()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public int QueueTypeId { get; set; }

        public int UserId { get; set; }

        public int ListId { get; set; }

        public DateTime DateSubmitted { get; set; }

        public DateTime? LastUpdate { get; set; }

        public DateTime? DateStart { get; set; }

        public DateTime? DateEnd { get; set; }

        public int? TotalRows { get; set; }

        public int? CurrentRow { get; set; }

        public bool IsDelete { get; set; }

        public bool IsJson { get; set; }

        public string RecordString { get; set; }

        public string ActionTitle { get; set; }

        public bool IsError { get; set; }

        public int? ProtectionId { get; set; }

        public int? CustomAttributeId { get; set; }

        public string Message { get; set; }

        public virtual User User { get; set; }

        public virtual List List { get; set; }

        public virtual Protection Protection { get; set; }

        public virtual CustomAttribute CustomAttribute { get; set; }

        public virtual QueueType QueueType { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            Queue obj = new Queue();
            obj.Id = Id;
            obj.QueueTypeId = QueueTypeId;
            obj.UserId = UserId;
            obj.ListId = ListId;
            obj.DateSubmitted = DateSubmitted;
            obj.LastUpdate = LastUpdate;
            obj.DateStart = DateStart;
            obj.DateEnd = DateEnd;
            obj.TotalRows = TotalRows;
            obj.CurrentRow = CurrentRow;
            obj.IsDelete = IsDelete;
            obj.IsJson = IsJson;
            obj.RecordString = RecordString;
            obj.ActionTitle = ActionTitle;
            obj.IsError = IsError;
            obj.ProtectionId = ProtectionId;
            obj.CustomAttributeId = CustomAttributeId;
            obj.Message = Message;
            return obj;
        }

        #endregion
    }

}
