//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class QueueType : ICloneable {

        public QueueType()
        {
            this.Queues = new List<Queue>();
            OnCreated();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public bool IsActive { get; set; }

        public int SortOrder { get; set; }

        public virtual IList<Queue> Queues { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            QueueType obj = new QueueType();
            obj.Id = Id;
            obj.Name = Name;
            obj.IsActive = IsActive;
            obj.SortOrder = SortOrder;
            return obj;
        }

        #endregion
    }

}
