//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class RefreshLog : ICloneable {

        public RefreshLog()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int UserId { get; set; }

        public virtual int ListId { get; set; }

        public virtual DateTime StartTimeStamp { get; set; }

        public virtual DateTime? EndTimeStamp { get; set; }

        public virtual bool Successful { get; set; }

        public virtual int RefreshStateId { get; set; }

        public virtual string JobName { get; set; }

        public virtual Guid? JobId { get; set; }

        public virtual bool? Copy { get; set; }

        public virtual int? SourceList { get; set; }

        public virtual string ErrorMessage { get; set; }

        public virtual List List { get; set; }

        public virtual RefreshState RefreshState { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            RefreshLog obj = new RefreshLog();
            obj.Id = Id;
            obj.UserId = UserId;
            obj.ListId = ListId;
            obj.StartTimeStamp = StartTimeStamp;
            obj.EndTimeStamp = EndTimeStamp;
            obj.Successful = Successful;
            obj.RefreshStateId = RefreshStateId;
            obj.JobName = JobName;
            obj.JobId = JobId;
            obj.Copy = Copy;
            obj.SourceList = SourceList;
            obj.ErrorMessage = ErrorMessage;
            return obj;
        }

        #endregion
    }

}
