//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class SavedObject : ICloneable {

        public SavedObject()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int UserId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Description { get; set; }

        public virtual string StoredObject { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            SavedObject obj = new SavedObject();
            obj.Id = Id;
            obj.UserId = UserId;
            obj.Name = Name;
            obj.Description = Description;
            obj.StoredObject = StoredObject;
            return obj;
        }

        #endregion
    }

}
