//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class User : ICloneable {

        public User()
        {
            this.CustomAttributes = new List<CustomAttribute>();
            this.ListUserRoles = new List<ListUserRole>();
            this.RefreshLogs = new List<RefreshLog>();
            this.UserRoles = new List<UserRole>();
            this.SavedObjects = new List<SavedObject>();
            this.ImportAttribs = new List<ImportAttrib>();
            this.FilterAuditLogs = new List<FilterAuditLog>();
            this.Queues = new List<Queue>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string VuNetId { get; set; }

        public virtual string FirstName { get; set; }

        public virtual string LastName { get; set; }

        public virtual string Email { get; set; }

        public virtual string CreateUser { get; set; }

        public virtual DateTime CreateDate { get; set; }

        public virtual DateTime? LastLoginDate { get; set; }

        public virtual int? LastListId { get; set; }

        public virtual IList<CustomAttribute> CustomAttributes { get; set; }

        public virtual IList<ListUserRole> ListUserRoles { get; set; }

        public virtual IList<RefreshLog> RefreshLogs { get; set; }

        public virtual IList<UserRole> UserRoles { get; set; }

        public virtual IList<SavedObject> SavedObjects { get; set; }

        public virtual IList<ImportAttrib> ImportAttribs { get; set; }

        public virtual IList<FilterAuditLog> FilterAuditLogs { get; set; }

        public virtual IList<Queue> Queues { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            User obj = new User();
            obj.Id = Id;
            obj.VuNetId = VuNetId;
            obj.FirstName = FirstName;
            obj.LastName = LastName;
            obj.Email = Email;
            obj.CreateUser = CreateUser;
            obj.CreateDate = CreateDate;
            obj.LastLoginDate = LastLoginDate;
            obj.LastListId = LastListId;
            return obj;
        }

        #endregion
    }

}
