//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class VwCombinedAppPool : ICloneable {

        public VwCombinedAppPool()
        {
            OnCreated();
        }

        public Guid APPLICATIONID { get; set; }

        public Guid PERSONID { get; set; }

        public string SLATEREFID { get; set; }

        public string EMPLID { get; set; }

        public string PSADMAPPLNBR { get; set; }

        public string FIRSTNAME { get; set; }

        public string MIDDLENAME { get; set; }

        public string LASTNAME { get; set; }

        public string SEX { get; set; }

        public DateTime? DOB { get; set; }

        public string SOC { get; set; }

        public string IPEDSETHNICCODE { get; set; }

        public string CITIZENSHIPSTATUS { get; set; }

        public string PRIMARYCITIZENSHIPCOUNTRY { get; set; }

        public string SECONDARYCITIZENSHIPCOUNTRY { get; set; }

        public string ROUNDKEY { get; set; }

        public string ADMITTYPE { get; set; }

        public string DECISIONCONFIRMEDDESCR { get; set; }

        public string DECISIONCONFIRMEDREASONDESCR { get; set; }

        public string DECISIONCONFIRMEDCODE { get; set; }

        public string DECISIONCONFIRMEDREASONEXPORTKEY { get; set; }

        public string APPLICATIONADMITTERM { get; set; }

        public string OUAGEOMARKET { get; set; }

        public string OUAREGION { get; set; }

        public string HSNAME { get; set; }

        public string STAFFASSIGNED { get; set; }

        public string ETSCODE { get; set; }

        public string HSSTATE { get; set; }

        public string HSRATING { get; set; }

        public string SCHOOLOFCHOICE1 { get; set; }

        public string SCHOOLOFCHOICE1DESCR { get; set; }

        public string SCHOOL1MAJOR1 { get; set; }

        public string SCHOOL1MAJOR1DESCR { get; set; }

        public string GPCMAJOR { get; set; }

        public string FINANCIALAIDINTEREST { get; set; }

        public string PELLELIGIBLE { get; set; }

        public string FACSTAFF { get; set; }

        public string LEGACY { get; set; }

        public string GIASTATUS { get; set; }

        public string FIRSTGEN { get; set; }

        public string POSSE { get; set; }

        public string CHICAGOSCHOLAR { get; set; }

        public string QUESTBRIDGE { get; set; }

        public string MOSAIC { get; set; }

        public string SCHFREEZE { get; set; }

        public string CORNELIUSVANDERBILTAPPLIED { get; set; }

        public string INGRAMAPPLIED { get; set; }

        public string CHANCELLORSAPPLIED { get; set; }

        public DateTime APPLICATIONUPDATE { get; set; }

        public DateTime PERSONUPDATE { get; set; }

        public DateTime? DECISIONUPDATE { get; set; }

        public DateTime? ACTUPDATE { get; set; }

        public DateTime? SCHOOLUPDATE { get; set; }

        public string LANDSCAPEHSNEIGHBORHOOD { get; set; }

        public string LANDSCAPESTDNTNEIGHBORHOOD { get; set; }

        public string SUBMITTINGTESTING { get; set; }

        public string COURSEWORKRIGOR { get; set; }

        public string RURALHS { get; set; }

        public string DACAUNDOCUMENTED { get; set; }

        public string KIPP { get; set; }

        public string NATLMERITAWARD { get; set; }

        public string CGRADEHS { get; set; }

        public string CGRADECOL { get; set; }

        public int? INSTITUTIONALNEED { get; set; }

        public string ORIGINALROUNDAPPLIED { get; set; }

        public string CHDIVERSITY { get; set; }

        public string CHBRIDGINGGAPS { get; set; }

        public string CHLEADERSHIP { get; set; }

        public string CHOVERALL { get; set; }

        public string WAITLISTLETTER { get; set; }

        public string INTLHIGHSCHOOL { get; set; }

        public int APPCOMPLETE { get; set; }

        public string SATRADMISSIONSSCORE { get; set; }

        public float? SATRHIGHESTVERIFIEDMAXERW { get; set; }

        public float? SATRHIGHESTVERIFIEDMAXMATH { get; set; }

        public string ACTADMISSIONSSCORE { get; set; }

        public float? ACTHIGHESTVERIFIEDTOTALENGLISH { get; set; }

        public float? ACTHIGHESTVERIFIEDTOTALMATH { get; set; }

        public string RIC { get; set; }

        public string ERIC { get; set; }

        public string HSGPACALCULATED { get; set; }

        public string LATESTEVAL { get; set; }

        public string EVALUATIONSTATUS { get; set; }

        public string EVALSTATUSDESCR { get; set; }

        public string AR { get; set; }

        public string ARVAL { get; set; }

        public string PR { get; set; }

        public string PRVAL { get; set; }

        public string SF { get; set; }

        public string SFVAL { get; set; }

        public string OVR { get; set; }

        public string OVRVAL { get; set; }

        public string WAITLISTACTIVEDATE { get; set; }

        public string WLSTRONG { get; set; }

        public string WLSTRONGDATE { get; set; }

        public string WAITLISTCHALLENGE1 { get; set; }

        public string WAITLISTCHALLENGE2 { get; set; }

        public string WAITLISTCHALLENGE3 { get; set; }

        public string WAITLISTCHALLENGE4 { get; set; }

        public string WAITLISTCHALLENGE5 { get; set; }

        public string WAITLISTCHALLENGE6 { get; set; }

        public string WAITLISTCHALLENGE7 { get; set; }

        public string WAITLISTCHALLENGE8 { get; set; }

        public string WAITLISTCHALLENGE9 { get; set; }

        public string WAITLISTPREOFFER { get; set; }

        public string WAITLISTPREOFFERRESPONSE { get; set; }

        public string EVER4YR { get; set; }

        public string MULTIPLECOLLEGES { get; set; }

        public string NUMBERCOLLEGES { get; set; }

        public string HSGRADYR { get; set; }

        public string CURRENTCOLLINTL { get; set; }

        public string COLLEGECREDITS { get; set; }

        public float? SCHOOL1HOURS { get; set; }

        public string HOURSTYPE1 { get; set; }

        public float? SCHOOL2HOURS { get; set; }

        public string HOURSTYPE2 { get; set; }

        public float? SCHOOL3HOURS { get; set; }

        public string HOURSTYPE3 { get; set; }

        public float? SCHOOL4HOURS { get; set; }

        public string HOURSTYPE4 { get; set; }

        public string UWCSCHOOL { get; set; }

        public string TITLEONESCHOOL { get; set; }

        public int? WAITLISTSTRONGNUMBER { get; set; }

        public string LC { get; set; }

        public string LCVAL { get; set; }

        public string CS { get; set; }

        public string CSVAL { get; set; }

        public string UB { get; set; }

        public string UBVAL { get; set; }

        public string DG { get; set; }

        public double? HSR { get; set; }

        public int FOCUSSCHOOL { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            VwCombinedAppPool obj = new VwCombinedAppPool();
            obj.APPLICATIONID = APPLICATIONID;
            obj.PERSONID = PERSONID;
            obj.SLATEREFID = SLATEREFID;
            obj.EMPLID = EMPLID;
            obj.PSADMAPPLNBR = PSADMAPPLNBR;
            obj.FIRSTNAME = FIRSTNAME;
            obj.MIDDLENAME = MIDDLENAME;
            obj.LASTNAME = LASTNAME;
            obj.SEX = SEX;
            obj.DOB = DOB;
            obj.SOC = SOC;
            obj.IPEDSETHNICCODE = IPEDSETHNICCODE;
            obj.CITIZENSHIPSTATUS = CITIZENSHIPSTATUS;
            obj.PRIMARYCITIZENSHIPCOUNTRY = PRIMARYCITIZENSHIPCOUNTRY;
            obj.SECONDARYCITIZENSHIPCOUNTRY = SECONDARYCITIZENSHIPCOUNTRY;
            obj.ROUNDKEY = ROUNDKEY;
            obj.ADMITTYPE = ADMITTYPE;
            obj.DECISIONCONFIRMEDDESCR = DECISIONCONFIRMEDDESCR;
            obj.DECISIONCONFIRMEDREASONDESCR = DECISIONCONFIRMEDREASONDESCR;
            obj.DECISIONCONFIRMEDCODE = DECISIONCONFIRMEDCODE;
            obj.DECISIONCONFIRMEDREASONEXPORTKEY = DECISIONCONFIRMEDREASONEXPORTKEY;
            obj.APPLICATIONADMITTERM = APPLICATIONADMITTERM;
            obj.OUAGEOMARKET = OUAGEOMARKET;
            obj.OUAREGION = OUAREGION;
            obj.HSNAME = HSNAME;
            obj.STAFFASSIGNED = STAFFASSIGNED;
            obj.ETSCODE = ETSCODE;
            obj.HSSTATE = HSSTATE;
            obj.HSRATING = HSRATING;
            obj.SCHOOLOFCHOICE1 = SCHOOLOFCHOICE1;
            obj.SCHOOLOFCHOICE1DESCR = SCHOOLOFCHOICE1DESCR;
            obj.SCHOOL1MAJOR1 = SCHOOL1MAJOR1;
            obj.SCHOOL1MAJOR1DESCR = SCHOOL1MAJOR1DESCR;
            obj.GPCMAJOR = GPCMAJOR;
            obj.FINANCIALAIDINTEREST = FINANCIALAIDINTEREST;
            obj.PELLELIGIBLE = PELLELIGIBLE;
            obj.FACSTAFF = FACSTAFF;
            obj.LEGACY = LEGACY;
            obj.GIASTATUS = GIASTATUS;
            obj.FIRSTGEN = FIRSTGEN;
            obj.POSSE = POSSE;
            obj.CHICAGOSCHOLAR = CHICAGOSCHOLAR;
            obj.QUESTBRIDGE = QUESTBRIDGE;
            obj.MOSAIC = MOSAIC;
            obj.SCHFREEZE = SCHFREEZE;
            obj.CORNELIUSVANDERBILTAPPLIED = CORNELIUSVANDERBILTAPPLIED;
            obj.INGRAMAPPLIED = INGRAMAPPLIED;
            obj.CHANCELLORSAPPLIED = CHANCELLORSAPPLIED;
            obj.APPLICATIONUPDATE = APPLICATIONUPDATE;
            obj.PERSONUPDATE = PERSONUPDATE;
            obj.DECISIONUPDATE = DECISIONUPDATE;
            obj.ACTUPDATE = ACTUPDATE;
            obj.SCHOOLUPDATE = SCHOOLUPDATE;
            obj.LANDSCAPEHSNEIGHBORHOOD = LANDSCAPEHSNEIGHBORHOOD;
            obj.LANDSCAPESTDNTNEIGHBORHOOD = LANDSCAPESTDNTNEIGHBORHOOD;
            obj.SUBMITTINGTESTING = SUBMITTINGTESTING;
            obj.COURSEWORKRIGOR = COURSEWORKRIGOR;
            obj.RURALHS = RURALHS;
            obj.DACAUNDOCUMENTED = DACAUNDOCUMENTED;
            obj.KIPP = KIPP;
            obj.NATLMERITAWARD = NATLMERITAWARD;
            obj.CGRADEHS = CGRADEHS;
            obj.CGRADECOL = CGRADECOL;
            obj.INSTITUTIONALNEED = INSTITUTIONALNEED;
            obj.ORIGINALROUNDAPPLIED = ORIGINALROUNDAPPLIED;
            obj.CHDIVERSITY = CHDIVERSITY;
            obj.CHBRIDGINGGAPS = CHBRIDGINGGAPS;
            obj.CHLEADERSHIP = CHLEADERSHIP;
            obj.CHOVERALL = CHOVERALL;
            obj.WAITLISTLETTER = WAITLISTLETTER;
            obj.INTLHIGHSCHOOL = INTLHIGHSCHOOL;
            obj.APPCOMPLETE = APPCOMPLETE;
            obj.SATRADMISSIONSSCORE = SATRADMISSIONSSCORE;
            obj.SATRHIGHESTVERIFIEDMAXERW = SATRHIGHESTVERIFIEDMAXERW;
            obj.SATRHIGHESTVERIFIEDMAXMATH = SATRHIGHESTVERIFIEDMAXMATH;
            obj.ACTADMISSIONSSCORE = ACTADMISSIONSSCORE;
            obj.ACTHIGHESTVERIFIEDTOTALENGLISH = ACTHIGHESTVERIFIEDTOTALENGLISH;
            obj.ACTHIGHESTVERIFIEDTOTALMATH = ACTHIGHESTVERIFIEDTOTALMATH;
            obj.RIC = RIC;
            obj.ERIC = ERIC;
            obj.HSGPACALCULATED = HSGPACALCULATED;
            obj.LATESTEVAL = LATESTEVAL;
            obj.EVALUATIONSTATUS = EVALUATIONSTATUS;
            obj.EVALSTATUSDESCR = EVALSTATUSDESCR;
            obj.AR = AR;
            obj.ARVAL = ARVAL;
            obj.PR = PR;
            obj.PRVAL = PRVAL;
            obj.SF = SF;
            obj.SFVAL = SFVAL;
            obj.OVR = OVR;
            obj.OVRVAL = OVRVAL;
            obj.WAITLISTACTIVEDATE = WAITLISTACTIVEDATE;
            obj.WLSTRONG = WLSTRONG;
            obj.WLSTRONGDATE = WLSTRONGDATE;
            obj.WAITLISTCHALLENGE1 = WAITLISTCHALLENGE1;
            obj.WAITLISTCHALLENGE2 = WAITLISTCHALLENGE2;
            obj.WAITLISTCHALLENGE3 = WAITLISTCHALLENGE3;
            obj.WAITLISTCHALLENGE4 = WAITLISTCHALLENGE4;
            obj.WAITLISTCHALLENGE5 = WAITLISTCHALLENGE5;
            obj.WAITLISTCHALLENGE6 = WAITLISTCHALLENGE6;
            obj.WAITLISTCHALLENGE7 = WAITLISTCHALLENGE7;
            obj.WAITLISTCHALLENGE8 = WAITLISTCHALLENGE8;
            obj.WAITLISTCHALLENGE9 = WAITLISTCHALLENGE9;
            obj.WAITLISTPREOFFER = WAITLISTPREOFFER;
            obj.WAITLISTPREOFFERRESPONSE = WAITLISTPREOFFERRESPONSE;
            obj.EVER4YR = EVER4YR;
            obj.MULTIPLECOLLEGES = MULTIPLECOLLEGES;
            obj.NUMBERCOLLEGES = NUMBERCOLLEGES;
            obj.HSGRADYR = HSGRADYR;
            obj.CURRENTCOLLINTL = CURRENTCOLLINTL;
            obj.COLLEGECREDITS = COLLEGECREDITS;
            obj.SCHOOL1HOURS = SCHOOL1HOURS;
            obj.HOURSTYPE1 = HOURSTYPE1;
            obj.SCHOOL2HOURS = SCHOOL2HOURS;
            obj.HOURSTYPE2 = HOURSTYPE2;
            obj.SCHOOL3HOURS = SCHOOL3HOURS;
            obj.HOURSTYPE3 = HOURSTYPE3;
            obj.SCHOOL4HOURS = SCHOOL4HOURS;
            obj.HOURSTYPE4 = HOURSTYPE4;
            obj.UWCSCHOOL = UWCSCHOOL;
            obj.TITLEONESCHOOL = TITLEONESCHOOL;
            obj.WAITLISTSTRONGNUMBER = WAITLISTSTRONGNUMBER;
            obj.LC = LC;
            obj.LCVAL = LCVAL;
            obj.CS = CS;
            obj.CSVAL = CSVAL;
            obj.UB = UB;
            obj.UBVAL = UBVAL;
            obj.DG = DG;
            obj.HSR = HSR;
            obj.FOCUSSCHOOL = FOCUSSCHOOL;
            return obj;
        }

        #endregion
    }

}
