//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class VwDropdownAttributeGrid : ICloneable {

        public VwDropdownAttributeGrid()
        {
            OnCreated();
        }

        public virtual int AttributeId { get; set; }

        public virtual string AttributeName { get; set; }

        public virtual DateTime? DateCreated { get; set; }

        public virtual int? CreatedByUserId { get; set; }

        public virtual string CreatedByUserName { get; set; }

        public virtual string CreatedByUserEmail { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            VwDropdownAttributeGrid obj = new VwDropdownAttributeGrid();
            obj.AttributeId = AttributeId;
            obj.AttributeName = AttributeName;
            obj.DateCreated = DateCreated;
            obj.CreatedByUserId = CreatedByUserId;
            obj.CreatedByUserName = CreatedByUserName;
            obj.CreatedByUserEmail = CreatedByUserEmail;
            return obj;
        }

        #endregion
    }

}
