//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class VwHighSchool : ICloneable {

        public VwHighSchool()
        {
            OnCreated();
        }

        public virtual string Code { get; set; }

        public virtual string State { get; set; }

        public virtual string Name { get; set; }

        public virtual string Rating { get; set; }

        public virtual string Region { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            VwHighSchool obj = new VwHighSchool();
            obj.Code = Code;
            obj.State = State;
            obj.Name = Name;
            obj.Rating = Rating;
            obj.Region = Region;
            return obj;
        }

        #endregion
    }

}
