//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class VwListAttributeView : ICloneable {

        public VwListAttributeView()
        {
            OnCreated();
        }

        public virtual string UniqueId { get; set; }

        public virtual string CompositeId { get; set; }

        public virtual int ListId { get; set; }

        public virtual string ListName { get; set; }

        public virtual Guid ApplicationId { get; set; }

        public virtual Guid PersonId { get; set; }

        public virtual int AttributeId { get; set; }

        public virtual string AttributeName { get; set; }

        public virtual int? AttributeCreatedByUserId { get; set; }

        public virtual string AttributeCreatedByFirstName { get; set; }

        public virtual string AttributeCreatedByLastName { get; set; }

        public virtual DateTime? AttributeCreatedDate { get; set; }

        public virtual int LastModifiedByUserId { get; set; }

        public virtual string LastModifiedByFirstName { get; set; }

        public virtual string LastModifiedByLastName { get; set; }

        public virtual DateTime LastModifiedDate { get; set; }

        public virtual int? CountUsageInList { get; set; }

        public virtual int? CountTotalUsage { get; set; }

        public virtual string ApplicantFirstName { get; set; }

        public virtual string ApplicantLastName { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            VwListAttributeView obj = new VwListAttributeView();
            obj.UniqueId = UniqueId;
            obj.CompositeId = CompositeId;
            obj.ListId = ListId;
            obj.ListName = ListName;
            obj.ApplicationId = ApplicationId;
            obj.PersonId = PersonId;
            obj.AttributeId = AttributeId;
            obj.AttributeName = AttributeName;
            obj.AttributeCreatedByUserId = AttributeCreatedByUserId;
            obj.AttributeCreatedByFirstName = AttributeCreatedByFirstName;
            obj.AttributeCreatedByLastName = AttributeCreatedByLastName;
            obj.AttributeCreatedDate = AttributeCreatedDate;
            obj.LastModifiedByUserId = LastModifiedByUserId;
            obj.LastModifiedByFirstName = LastModifiedByFirstName;
            obj.LastModifiedByLastName = LastModifiedByLastName;
            obj.LastModifiedDate = LastModifiedDate;
            obj.CountUsageInList = CountUsageInList;
            obj.CountTotalUsage = CountTotalUsage;
            obj.ApplicantFirstName = ApplicantFirstName;
            obj.ApplicantLastName = ApplicantLastName;
            return obj;
        }

        #endregion
    }

}
