//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Sam Data Template
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Sam.DataModel
{
    public partial class VwListAttributeViewGrid : ICloneable {

        public VwListAttributeViewGrid()
        {
            OnCreated();
        }

        public virtual string UniqueId { get; set; }

        public virtual string CompositeId { get; set; }

        public virtual int AttributeId { get; set; }

        public virtual string AttributeName { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            VwListAttributeViewGrid obj = new VwListAttributeViewGrid();
            obj.UniqueId = UniqueId;
            obj.CompositeId = CompositeId;
            obj.AttributeId = AttributeId;
            obj.AttributeName = AttributeName;
            return obj;
        }

        #endregion
    }

}
