<Project Sdk="Microsoft.NET.Sdk.Web">


	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Telerik.UI.for.Blazor" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Sam.Common.Global\Sam.Common.Global.csproj" />
	  <ProjectReference Include="..\Sam.DataModel.FilterModel\Sam.DataModel.FilterModel.csproj" />
	  <ProjectReference Include="..\Sam.DataTransferObjects\Sam.DataTransferObjects.csproj" />
	</ItemGroup>

</Project>
